package com.fh.taolijie.domain.certi;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fh.taolijie.domain.Pageable;

import java.util.Date;

public class EmpCertiModel extends Pageable {
    private Integer id;

    private String companyName;
    private String compPhone;

    private Integer memberId;
    private String username;

    private String contactName;

    private Integer industryId;

    private String memo;

    private String address;

    private String picIds;

    private String status;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createdTime;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    public EmpCertiModel() {}
    public EmpCertiModel(int pn, int ps) {
        super(pn, ps);
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_certi.id
     *
     * @param id the value for emp_certi.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_certi.company_name
     *
     * @return the value of emp_certi.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_certi.company_name
     *
     * @param companyName the value for emp_certi.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_certi.address
     *
     * @return the value of emp_certi.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_certi.address
     *
     * @param address the value for emp_certi.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_certi.pic_ids
     *
     * @return the value of emp_certi.pic_ids
     *
     * @mbggenerated
     */
    public String getPicIds() {
        return picIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_certi.pic_ids
     *
     * @param picIds the value for emp_certi.pic_ids
     *
     * @mbggenerated
     */
    public void setPicIds(String picIds) {
        this.picIds = picIds == null ? null : picIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_certi.status
     *
     * @return the value of emp_certi.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_certi.status
     *
     * @param status the value for emp_certi.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_certi.created_time
     *
     * @return the value of emp_certi.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_certi.created_time
     *
     * @param createdTime the value for emp_certi.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_certi.update_time
     *
     * @return the value of emp_certi.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    public Integer getMemberId() {
        return memberId;
    }

    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Integer getIndustryId() {
        return industryId;
    }

    public void setIndustryId(Integer industryId) {
        this.industryId = industryId;
    }

    public String getCompPhone() {
        return compPhone;
    }

    public void setCompPhone(String compPhone) {
        this.compPhone = compPhone;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}