package com.fh.taolijie.domain;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.math.BigDecimal;
import java.util.Date;

public class AccFlowModel {
    private Integer id;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createdTime;

    private Integer accId;

    private String actionType;

    private BigDecimal avaBalanceCh;

    private BigDecimal froBalanceCh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_flow.tot_balance_ch
     *
     * @mbggenerated
     */
    private BigDecimal totBalanceCh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_flow.ava_balance_new
     *
     * @mbggenerated
     */
    private BigDecimal avaBalanceNew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_flow.fro_balance_new
     *
     * @mbggenerated
     */
    private BigDecimal froBalanceNew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_flow.tot_balance_new
     *
     * @mbggenerated
     */
    private BigDecimal totBalanceNew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_flow.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_flow.id
     *
     * @return the value of acc_flow.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_flow.id
     *
     * @param id the value for acc_flow.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_flow.created_time
     *
     * @return the value of acc_flow.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_flow.created_time
     *
     * @param createdTime the value for acc_flow.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_flow.acc_id
     *
     * @return the value of acc_flow.acc_id
     *
     * @mbggenerated
     */
    public Integer getAccId() {
        return accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_flow.acc_id
     *
     * @param accId the value for acc_flow.acc_id
     *
     * @mbggenerated
     */
    public void setAccId(Integer accId) {
        this.accId = accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_flow.action_type
     *
     * @return the value of acc_flow.action_type
     *
     * @mbggenerated
     */
    public String getActionType() {
        return actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_flow.action_type
     *
     * @param actionType the value for acc_flow.action_type
     *
     * @mbggenerated
     */
    public void setActionType(String actionType) {
        this.actionType = actionType == null ? null : actionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_flow.ava_balance_ch
     *
     * @return the value of acc_flow.ava_balance_ch
     *
     * @mbggenerated
     */
    public BigDecimal getAvaBalanceCh() {
        return avaBalanceCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_flow.ava_balance_ch
     *
     * @param avaBalanceCh the value for acc_flow.ava_balance_ch
     *
     * @mbggenerated
     */
    public void setAvaBalanceCh(BigDecimal avaBalanceCh) {
        this.avaBalanceCh = avaBalanceCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_flow.fro_balance_ch
     *
     * @return the value of acc_flow.fro_balance_ch
     *
     * @mbggenerated
     */
    public BigDecimal getFroBalanceCh() {
        return froBalanceCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_flow.fro_balance_ch
     *
     * @param froBalanceCh the value for acc_flow.fro_balance_ch
     *
     * @mbggenerated
     */
    public void setFroBalanceCh(BigDecimal froBalanceCh) {
        this.froBalanceCh = froBalanceCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_flow.tot_balance_ch
     *
     * @return the value of acc_flow.tot_balance_ch
     *
     * @mbggenerated
     */
    public BigDecimal getTotBalanceCh() {
        return totBalanceCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_flow.tot_balance_ch
     *
     * @param totBalanceCh the value for acc_flow.tot_balance_ch
     *
     * @mbggenerated
     */
    public void setTotBalanceCh(BigDecimal totBalanceCh) {
        this.totBalanceCh = totBalanceCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_flow.ava_balance_new
     *
     * @return the value of acc_flow.ava_balance_new
     *
     * @mbggenerated
     */
    public BigDecimal getAvaBalanceNew() {
        return avaBalanceNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_flow.ava_balance_new
     *
     * @param avaBalanceNew the value for acc_flow.ava_balance_new
     *
     * @mbggenerated
     */
    public void setAvaBalanceNew(BigDecimal avaBalanceNew) {
        this.avaBalanceNew = avaBalanceNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_flow.fro_balance_new
     *
     * @return the value of acc_flow.fro_balance_new
     *
     * @mbggenerated
     */
    public BigDecimal getFroBalanceNew() {
        return froBalanceNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_flow.fro_balance_new
     *
     * @param froBalanceNew the value for acc_flow.fro_balance_new
     *
     * @mbggenerated
     */
    public void setFroBalanceNew(BigDecimal froBalanceNew) {
        this.froBalanceNew = froBalanceNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_flow.tot_balance_new
     *
     * @return the value of acc_flow.tot_balance_new
     *
     * @mbggenerated
     */
    public BigDecimal getTotBalanceNew() {
        return totBalanceNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_flow.tot_balance_new
     *
     * @param totBalanceNew the value for acc_flow.tot_balance_new
     *
     * @mbggenerated
     */
    public void setTotBalanceNew(BigDecimal totBalanceNew) {
        this.totBalanceNew = totBalanceNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_flow.memo
     *
     * @return the value of acc_flow.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_flow.memo
     *
     * @param memo the value for acc_flow.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}