package com.fh.taolijie.domain;

import java.util.Date;

public class BannerPicModel extends Pageable {
    private Integer id;

    private Date createdTime;

    private Integer pictureId;

    private Integer orderIndex;

    private String url;
    private String memo;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_pic.id
     *
     * @return the value of banner_pic.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_pic.id
     *
     * @param id the value for banner_pic.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getOrderIndex() {
        return orderIndex;
    }

    public void setOrder(Integer order) {
        this.orderIndex = order;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_pic.time
     *
     * @return the value of banner_pic.time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_pic.time
     *
     * @param time the value for banner_pic.time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date time) {
        this.createdTime = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_pic.picture_id
     *
     * @return the value of banner_pic.picture_id
     *
     * @mbggenerated
     */
    public Integer getPictureId() {
        return pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_pic.picture_id
     *
     * @param pictureId the value for banner_pic.picture_id
     *
     * @mbggenerated
     */
    public void setPictureId(Integer pictureId) {
        this.pictureId = pictureId;
    }
}