package com.fh.taolijie.domain;

public class NewsModelWithBLOBs extends NewsModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.picture_path
     *
     * @mbggenerated
     */
    private String picturePath;

    public NewsModelWithBLOBs() {}
    public NewsModelWithBLOBs(int number, int size) {
        super(number, size);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.picture_path
     *
     * @return the value of news.picture_path
     *
     * @mbggenerated
     */
    public String getPicturePath() {
        return picturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.picture_path
     *
     * @param picturePath the value for news.picture_path
     *
     * @mbggenerated
     */
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath == null ? null : picturePath.trim();
    }
}