package com.fh.taolijie.domain;

import com.fh.taolijie.domain.v2.SchoolActModel;
import com.fh.taolijie.domain.v2.TaoliIvyModel;

import java.util.Date;

public class ParticipantModel extends Pageable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participant.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participant.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;
    private MemberModel member;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participant.ivy_id
     *
     * @mbggenerated
     */
    private Integer ivyId;
    private TaoliIvyModel ivy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participant.activity_id
     *
     * @mbggenerated
     */
    private Integer activityId;
    private SchoolActModel act;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participant.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participant.academy
     *
     * @mbggenerated
     */
    private String academy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participant.class
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participant.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participant.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participant.weichat
     *
     * @mbggenerated
     */
    private String weichat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participant.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participant.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participant.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participant.id
     *
     * @return the value of participant.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participant.id
     *
     * @param id the value for participant.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public MemberModel getMember() {
        return member;
    }

    public void setMember(MemberModel member) {
        this.member = member;
    }

    public TaoliIvyModel getIvy() {
        return ivy;
    }

    public void setIvy(TaoliIvyModel ivy) {
        this.ivy = ivy;
    }

    public SchoolActModel getAct() {
        return act;
    }

    public void setAct(SchoolActModel act) {
        this.act = act;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participant.member_id
     *
     * @return the value of participant.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participant.member_id
     *
     * @param memberId the value for participant.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participant.ivy_id
     *
     * @return the value of participant.ivy_id
     *
     * @mbggenerated
     */
    public Integer getIvyId() {
        return ivyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participant.ivy_id
     *
     * @param ivyId the value for participant.ivy_id
     *
     * @mbggenerated
     */
    public void setIvyId(Integer ivyId) {
        this.ivyId = ivyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participant.activity_id
     *
     * @return the value of participant.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participant.activity_id
     *
     * @param activityId the value for participant.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participant.name
     *
     * @return the value of participant.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participant.name
     *
     * @param name the value for participant.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participant.academy
     *
     * @return the value of participant.academy
     *
     * @mbggenerated
     */
    public String getAcademy() {
        return academy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participant.academy
     *
     * @param academy the value for participant.academy
     *
     * @mbggenerated
     */
    public void setAcademy(String academy) {
        this.academy = academy == null ? null : academy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participant.class
     *
     * @return the value of participant.class
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participant.class
     *
     * @param class the value for participant.class
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participant.qq
     *
     * @return the value of participant.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participant.qq
     *
     * @param qq the value for participant.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participant.phone
     *
     * @return the value of participant.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participant.phone
     *
     * @param phone the value for participant.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participant.weichat
     *
     * @return the value of participant.weichat
     *
     * @mbggenerated
     */
    public String getWeichat() {
        return weichat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participant.weichat
     *
     * @param weichat the value for participant.weichat
     *
     * @mbggenerated
     */
    public void setWeichat(String weichat) {
        this.weichat = weichat == null ? null : weichat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participant.email
     *
     * @return the value of participant.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participant.email
     *
     * @param email the value for participant.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participant.gender
     *
     * @return the value of participant.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participant.gender
     *
     * @param gender the value for participant.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participant.created_time
     *
     * @return the value of participant.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participant.created_time
     *
     * @param createdTime the value for participant.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}