package com.fh.taolijie.domain;

public class QuestProRel {
    private Integer id;

    private Integer provinceId;

    private Integer questId;

    private String provinceName;

    public QuestProRel() {}

    public QuestProRel(Integer questId, Integer provinceId) {
        this.questId = questId;
        this.provinceId = provinceId;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getProvinceName() {
        return provinceName;
    }

    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_province_rel.province_id
     *
     * @param provinceId the value for quest_province_rel.province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    public Integer getQuestId() {
        return questId;
    }

    public void setQuestId(Integer questId) {
        this.questId = questId;
    }
}