package com.fh.taolijie.domain;

public class QuestSchRelModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_school_rel.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_school_rel.quest_id
     *
     * @mbggenerated
     */
    private Integer questId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_school_rel.school_id
     *
     * @mbggenerated
     */
    private Integer schoolId;

    public QuestSchRelModel(Integer questId, Integer schoolId) {
        this.questId = questId;
        this.schoolId = schoolId;
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_school_rel.id
     *
     * @param id the value for quest_school_rel.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_school_rel.quest_id
     *
     * @return the value of quest_school_rel.quest_id
     *
     * @mbggenerated
     */
    public Integer getQuestId() {
        return questId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_school_rel.quest_id
     *
     * @param questId the value for quest_school_rel.quest_id
     *
     * @mbggenerated
     */
    public void setQuestId(Integer questId) {
        this.questId = questId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_school_rel.school_id
     *
     * @return the value of quest_school_rel.school_id
     *
     * @mbggenerated
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_school_rel.school_id
     *
     * @param schoolId the value for quest_school_rel.school_id
     *
     * @mbggenerated
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }
}