package com.fh.taolijie.domain;

public class QuestionOptModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_opt.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_opt.opt_name
     *
     * @mbggenerated
     */
    private String optName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_opt.opt_content
     *
     * @mbggenerated
     */
    private String optContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_opt.question_id
     *
     * @mbggenerated
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_opt.answer_amt
     *
     * @mbggenerated
     */
    private Integer answerAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_opt.correct
     *
     * @mbggenerated
     */
    private Boolean correct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_opt.order_index
     *
     * @mbggenerated
     */
    private Integer orderIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_opt.id
     *
     * @return the value of question_opt.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_opt.id
     *
     * @param id the value for question_opt.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_opt.opt_name
     *
     * @return the value of question_opt.opt_name
     *
     * @mbggenerated
     */
    public String getOptName() {
        return optName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_opt.opt_name
     *
     * @param optName the value for question_opt.opt_name
     *
     * @mbggenerated
     */
    public void setOptName(String optName) {
        this.optName = optName == null ? null : optName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_opt.opt_content
     *
     * @return the value of question_opt.opt_content
     *
     * @mbggenerated
     */
    public String getOptContent() {
        return optContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_opt.opt_content
     *
     * @param optContent the value for question_opt.opt_content
     *
     * @mbggenerated
     */
    public void setOptContent(String optContent) {
        this.optContent = optContent == null ? null : optContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_opt.question_id
     *
     * @return the value of question_opt.question_id
     *
     * @mbggenerated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_opt.question_id
     *
     * @param questionId the value for question_opt.question_id
     *
     * @mbggenerated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_opt.answer_amt
     *
     * @return the value of question_opt.answer_amt
     *
     * @mbggenerated
     */
    public Integer getAnswerAmt() {
        return answerAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_opt.answer_amt
     *
     * @param answerAmt the value for question_opt.answer_amt
     *
     * @mbggenerated
     */
    public void setAnswerAmt(Integer answerAmt) {
        this.answerAmt = answerAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_opt.correct
     *
     * @return the value of question_opt.correct
     *
     * @mbggenerated
     */
    public Boolean getCorrect() {
        return correct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_opt.correct
     *
     * @param correct the value for question_opt.correct
     *
     * @mbggenerated
     */
    public void setCorrect(Boolean correct) {
        this.correct = correct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_opt.order_index
     *
     * @return the value of question_opt.order_index
     *
     * @mbggenerated
     */
    public Integer getOrderIndex() {
        return orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_opt.order_index
     *
     * @param orderIndex the value for question_opt.order_index
     *
     * @mbggenerated
     */
    public void setOrderIndex(Integer orderIndex) {
        this.orderIndex = orderIndex;
    }
}