package com.fh.taolijie.domain;

import java.math.BigDecimal;
import java.util.Date;

public class QuestModel {
    private Integer id;

    private String title;

    private Date createdTime;

    private Integer questCateId;

    private Date startTime;

    private Date endTime;

    private Integer limitTime;

    private Integer totalAmt;

    private Integer leftAmt;

    private BigDecimal award;

    private Integer memberId;

    private BigDecimal finalAward;

    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.contact_phone
     *
     * @mbggenerated
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.quest_detail
     *
     * @mbggenerated
     */
    private String questDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.memo
     *
     * @mbggenerated
     */
    private String memo;

    private Boolean offline;

    private Integer provinceId;
    private Integer cityId;
    private Integer regionId;
    private Integer collegeId;
    private Integer schoolId;


    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.id
     *
     * @param id the value for quest.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.title
     *
     * @return the value of quest.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.title
     *
     * @param title the value for quest.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.created_time
     *
     * @return the value of quest.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.created_time
     *
     * @param createdTime the value for quest.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.quest_cate_id
     *
     * @return the value of quest.quest_cate_id
     *
     * @mbggenerated
     */
    public Integer getQuestCateId() {
        return questCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.quest_cate_id
     *
     * @param questCateId the value for quest.quest_cate_id
     *
     * @mbggenerated
     */
    public void setQuestCateId(Integer questCateId) {
        this.questCateId = questCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.start_time
     *
     * @return the value of quest.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.start_time
     *
     * @param startTime the value for quest.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.end_time
     *
     * @return the value of quest.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.end_time
     *
     * @param endTime the value for quest.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.limit_time
     *
     * @return the value of quest.limit_time
     *
     * @mbggenerated
     */
    public Integer getLimitTime() {
        return limitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.limit_time
     *
     * @param limitTime the value for quest.limit_time
     *
     * @mbggenerated
     */
    public void setLimitTime(Integer limitTime) {
        this.limitTime = limitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.total_amt
     *
     * @return the value of quest.total_amt
     *
     * @mbggenerated
     */
    public Integer getTotalAmt() {
        return totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.total_amt
     *
     * @param totalAmt the value for quest.total_amt
     *
     * @mbggenerated
     */
    public void setTotalAmt(Integer totalAmt) {
        this.totalAmt = totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.left_amt
     *
     * @return the value of quest.left_amt
     *
     * @mbggenerated
     */
    public Integer getLeftAmt() {
        return leftAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.left_amt
     *
     * @param leftAmt the value for quest.left_amt
     *
     * @mbggenerated
     */
    public void setLeftAmt(Integer leftAmt) {
        this.leftAmt = leftAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.award
     *
     * @return the value of quest.award
     *
     * @mbggenerated
     */
    public BigDecimal getAward() {
        return award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.award
     *
     * @param award the value for quest.award
     *
     * @mbggenerated
     */
    public void setAward(BigDecimal award) {
        this.award = award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.contact_name
     *
     * @return the value of quest.contact_name
     *
     * @mbggenerated
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.contact_name
     *
     * @param contactName the value for quest.contact_name
     *
     * @mbggenerated
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.contact_phone
     *
     * @return the value of quest.contact_phone
     *
     * @mbggenerated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.contact_phone
     *
     * @param contactPhone the value for quest.contact_phone
     *
     * @mbggenerated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.description
     *
     * @return the value of quest.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.description
     *
     * @param description the value for quest.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.quest_detail
     *
     * @return the value of quest.quest_detail
     *
     * @mbggenerated
     */
    public String getQuestDetail() {
        return questDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.quest_detail
     *
     * @param questDetail the value for quest.quest_detail
     *
     * @mbggenerated
     */
    public void setQuestDetail(String questDetail) {
        this.questDetail = questDetail == null ? null : questDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.url
     *
     * @return the value of quest.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.url
     *
     * @param url the value for quest.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.memo
     *
     * @return the value of quest.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.memo
     *
     * @param memo the value for quest.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.offline
     *
     * @return the value of quest.offline
     *
     * @mbggenerated
     */
    public Boolean getOffline() {
        return offline;
    }

    public Integer getProvinceId() {
        return provinceId;
    }

    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    public Integer getCityId() {
        return cityId;
    }

    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    public Integer getRegionId() {
        return regionId;
    }

    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    public Integer getCollegeId() {
        return collegeId;
    }

    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }

    public Integer getSchoolId() {
        return schoolId;
    }

    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    public BigDecimal getFinalAward() {
        return finalAward;
    }

    public Integer getMemberId() {
        return memberId;
    }

    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    public void setFinalAward(BigDecimal finalAward) {
        this.finalAward = finalAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.offline
     *
     * @param offline the value for quest.offline
     *
     * @mbggenerated
     */
    public void setOffline(Boolean offline) {
        this.offline = offline;
    }
}