package com.fh.taolijie.domain;

public class QuestProRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_province_rel.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_province_rel.province_id
     *
     * @mbggenerated
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest_province_rel.quest_id
     *
     * @mbggenerated
     */
    private String questId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_province_rel.id
     *
     * @return the value of quest_province_rel.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_province_rel.id
     *
     * @param id the value for quest_province_rel.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_province_rel.province_id
     *
     * @return the value of quest_province_rel.province_id
     *
     * @mbggenerated
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_province_rel.province_id
     *
     * @param provinceId the value for quest_province_rel.province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest_province_rel.quest_id
     *
     * @return the value of quest_province_rel.quest_id
     *
     * @mbggenerated
     */
    public String getQuestId() {
        return questId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest_province_rel.quest_id
     *
     * @param questId the value for quest_province_rel.quest_id
     *
     * @mbggenerated
     */
    public void setQuestId(String questId) {
        this.questId = questId == null ? null : questId.trim();
    }
}