package com.fh.taolijie.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

public class RecoPostModel extends Pageable {
    private Integer id;

    private Integer postId;

    private String title;

    private Integer type;

    private Integer memberId;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createdTime;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date auditTime;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date expiredTime;

    private Integer orderIndex;

    private Boolean valid;


    // ********查询用************
    @JsonIgnore
    private Boolean orderByIndex = true;
    @JsonIgnore
    private Boolean orderByTime = false;
    @JsonIgnore
    private int hours;

    public RecoPostModel(int pn, int ps) {
        super(pn, ps);
    }

    public RecoPostModel() {

    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPostId() {
        return postId;
    }

    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getMemberId() {
        return memberId;
    }

    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    public Date getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    public Date getAuditTime() {
        return auditTime;
    }

    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reco_post.expired_time
     *
     * @return the value of reco_post.expired_time
     *
     * @mbggenerated
     */
    public Date getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reco_post.expired_time
     *
     * @param expiredTime the value for reco_post.expired_time
     *
     * @mbggenerated
     */
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }

    public Integer getOrderIndex() {
        return orderIndex;
    }

    public void setOrderIndex(Integer orderIndex) {
        this.orderIndex = orderIndex;
    }

    public Boolean getValid() {
        return valid;
    }

    public Boolean getOrderByIndex() {
        return orderByIndex;
    }

    public void setOrderByIndex(Boolean orderByIndex) {
        this.orderByIndex = orderByIndex;
    }

    public Boolean getOrderByTime() {
        return orderByTime;
    }

    public void setOrderByTime(Boolean orderByTime) {
        this.orderByTime = orderByTime;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getHours() {
        return hours;
    }

    public void setHours(int hours) {
        this.hours = hours;
    }

    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}