package com.fh.taolijie.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

public class RecoPostModel extends Pageable {
    private Integer id;

    private Integer postId;

    private Integer type;

    private Integer memberId;

    private Date createdTime;

    private Date auditTime;

    private Date expiredTime;

    private Integer orderIndex;

    private Boolean valid;


    // ********查询用************
    @JsonIgnore
    private Boolean orderByIndex = true;
    @JsonIgnore
    private Boolean orderByTime = false;

    public RecoPostModel(int pn, int ps) {
        super(pn, ps);
    }

    public RecoPostModel() {

    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reco_post.post_id
     *
     * @return the value of reco_post.post_id
     *
     * @mbggenerated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reco_post.post_id
     *
     * @param postId the value for reco_post.post_id
     *
     * @mbggenerated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reco_post.type
     *
     * @return the value of reco_post.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reco_post.type
     *
     * @param type the value for reco_post.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reco_post.member_id
     *
     * @return the value of reco_post.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reco_post.member_id
     *
     * @param memberId the value for reco_post.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reco_post.created_time
     *
     * @return the value of reco_post.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reco_post.created_time
     *
     * @param createdTime the value for reco_post.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reco_post.audit_time
     *
     * @return the value of reco_post.audit_time
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reco_post.audit_time
     *
     * @param auditTime the value for reco_post.audit_time
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reco_post.expired_time
     *
     * @return the value of reco_post.expired_time
     *
     * @mbggenerated
     */
    public Date getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reco_post.expired_time
     *
     * @param expiredTime the value for reco_post.expired_time
     *
     * @mbggenerated
     */
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reco_post.order_index
     *
     * @return the value of reco_post.order_index
     *
     * @mbggenerated
     */
    public Integer getOrderIndex() {
        return orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reco_post.order_index
     *
     * @param orderIndex the value for reco_post.order_index
     *
     * @mbggenerated
     */
    public void setOrderIndex(Integer orderIndex) {
        this.orderIndex = orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reco_post.valid
     *
     * @return the value of reco_post.valid
     *
     * @mbggenerated
     */
    public Boolean getValid() {
        return valid;
    }

    public Boolean getOrderByIndex() {
        return orderByIndex;
    }

    public void setOrderByIndex(Boolean orderByIndex) {
        this.orderByIndex = orderByIndex;
    }

    public Boolean getOrderByTime() {
        return orderByTime;
    }

    public void setOrderByTime(Boolean orderByTime) {
        this.orderByTime = orderByTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reco_post.valid
     *
     * @param valid the value for reco_post.valid
     *
     * @mbggenerated
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}