package com.fh.taolijie.domain;

public class SchoolOrgModelWithBLOBs extends SchoolOrgModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_organization.member_names
     *
     * @mbggenerated
     */
    private String memberNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_organization.bulletin
     *
     * @mbggenerated
     */
    private String bulletin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_organization.member_names
     *
     * @return the value of school_organization.member_names
     *
     * @mbggenerated
     */
    public String getMemberNames() {
        return memberNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_organization.member_names
     *
     * @param memberNames the value for school_organization.member_names
     *
     * @mbggenerated
     */
    public void setMemberNames(String memberNames) {
        this.memberNames = memberNames == null ? null : memberNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_organization.bulletin
     *
     * @return the value of school_organization.bulletin
     *
     * @mbggenerated
     */
    public String getBulletin() {
        return bulletin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_organization.bulletin
     *
     * @param bulletin the value for school_organization.bulletin
     *
     * @mbggenerated
     */
    public void setBulletin(String bulletin) {
        this.bulletin = bulletin == null ? null : bulletin.trim();
    }
}