package com.fh.taolijie.domain;

public class SeqJobModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seq_job.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seq_job.id
     *
     * @return the value of seq_job.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seq_job.id
     *
     * @param id the value for seq_job.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}