package com.fh.taolijie.domain;

import com.fh.taolijie.domain.middle.CategoryWithPost;

public class SHPostCategoryModel {
    private Integer id;

    private String name;

    private Integer level;

    private String themeColor;

    private String memo;

    public SHPostCategoryModel() {}

    public SHPostCategoryModel(CategoryWithPost with) {
        this.id = with.getPostId();
        this.name = with.getName();
        this.level = with.getLevel();
        this.themeColor = with.getThemeColor();
        this.memo = with.getMemo();
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand_post_category.name
     *
     * @return the value of second_hand_post_category.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand_post_category.name
     *
     * @param name the value for second_hand_post_category.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand_post_category.level
     *
     * @return the value of second_hand_post_category.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand_post_category.level
     *
     * @param level the value for second_hand_post_category.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand_post_category.theme_color
     *
     * @return the value of second_hand_post_category.theme_color
     *
     * @mbggenerated
     */
    public String getThemeColor() {
        return themeColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand_post_category.theme_color
     *
     * @param themeColor the value for second_hand_post_category.theme_color
     *
     * @mbggenerated
     */
    public void setThemeColor(String themeColor) {
        this.themeColor = themeColor == null ? null : themeColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand_post_category.memo
     *
     * @return the value of second_hand_post_category.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand_post_category.memo
     *
     * @param memo the value for second_hand_post_category.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}