package com.fh.taolijie.domain;

public class SHPostModelWithBLOBs extends SHPostModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand_post.picture_path
     *
     * @mbggenerated
     */
    private String picturePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_hand_post.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand_post.picture_path
     *
     * @return the value of second_hand_post.picture_path
     *
     * @mbggenerated
     */
    public String getPicturePath() {
        return picturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand_post.picture_path
     *
     * @param picturePath the value for second_hand_post.picture_path
     *
     * @mbggenerated
     */
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath == null ? null : picturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_hand_post.description
     *
     * @return the value of second_hand_post.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_hand_post.description
     *
     * @param description the value for second_hand_post.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}