package com.fh.taolijie.domain;

public class SysConfigModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.quest_fee_rate
     *
     * @mbggenerated
     */
    private Integer questFeeRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.id
     *
     * @return the value of sys_config.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.id
     *
     * @param id the value for sys_config.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.quest_fee_rate
     *
     * @return the value of sys_config.quest_fee_rate
     *
     * @mbggenerated
     */
    public Integer getQuestFeeRate() {
        return questFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.quest_fee_rate
     *
     * @param questFeeRate the value for sys_config.quest_fee_rate
     *
     * @mbggenerated
     */
    public void setQuestFeeRate(Integer questFeeRate) {
        this.questFeeRate = questFeeRate;
    }
}