package com.fh.taolijie.domain;

import java.util.Date;

public class SysNotificationModel extends Pageable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.is_read
     *
     * @mbggenerated
     */
    private Boolean isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.access_range
     *
     * @mbggenerated
     */
    private String accessRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_notification.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.id
     *
     * @return the value of system_notification.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.id
     *
     * @param id the value for system_notification.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.title
     *
     * @return the value of system_notification.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.title
     *
     * @param title the value for system_notification.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.is_read
     *
     * @return the value of system_notification.is_read
     *
     * @mbggenerated
     */
    public Boolean getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.is_read
     *
     * @param isRead the value for system_notification.is_read
     *
     * @mbggenerated
     */
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.time
     *
     * @return the value of system_notification.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.time
     *
     * @param time the value for system_notification.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.access_range
     *
     * @return the value of system_notification.access_range
     *
     * @mbggenerated
     */
    public String getAccessRange() {
        return accessRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.access_range
     *
     * @param accessRange the value for system_notification.access_range
     *
     * @mbggenerated
     */
    public void setAccessRange(String accessRange) {
        this.accessRange = accessRange == null ? null : accessRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_notification.content
     *
     * @return the value of system_notification.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_notification.content
     *
     * @param content the value for system_notification.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}