package com.fh.taolijie.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class TljAuditModel extends Pageable {

    private Integer id;

    private Integer questId;

    private String questTitle;

    private Integer totAmt;

    private Integer leftAmt;

    private Integer empId;

    private String empUsername;

    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createdTime;

    //******** 仅做为请求参数使用 ***********
    @JsonIgnore
    private Integer minAmt;
    @JsonIgnore
    private Integer maxAmt;
    //******** 仅做为请求参数使用 ***********

    public TljAuditModel() {}
    public TljAuditModel(int pn, int ps) {
        super(pn, ps);
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tlj_audit.id
     *
     * @param id the value for tlj_audit.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tlj_audit.quest_id
     *
     * @return the value of tlj_audit.quest_id
     *
     * @mbggenerated
     */
    public Integer getQuestId() {
        return questId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tlj_audit.quest_id
     *
     * @param questId the value for tlj_audit.quest_id
     *
     * @mbggenerated
     */
    public void setQuestId(Integer questId) {
        this.questId = questId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tlj_audit.quest_title
     *
     * @return the value of tlj_audit.quest_title
     *
     * @mbggenerated
     */
    public String getQuestTitle() {
        return questTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tlj_audit.quest_title
     *
     * @param questTitle the value for tlj_audit.quest_title
     *
     * @mbggenerated
     */
    public void setQuestTitle(String questTitle) {
        this.questTitle = questTitle == null ? null : questTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tlj_audit.tot_amt
     *
     * @return the value of tlj_audit.tot_amt
     *
     * @mbggenerated
     */
    public Integer getTotAmt() {
        return totAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tlj_audit.tot_amt
     *
     * @param totAmt the value for tlj_audit.tot_amt
     *
     * @mbggenerated
     */
    public void setTotAmt(Integer totAmt) {
        this.totAmt = totAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tlj_audit.left_amt
     *
     * @return the value of tlj_audit.left_amt
     *
     * @mbggenerated
     */
    public Integer getLeftAmt() {
        return leftAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tlj_audit.left_amt
     *
     * @param leftAmt the value for tlj_audit.left_amt
     *
     * @mbggenerated
     */
    public void setLeftAmt(Integer leftAmt) {
        this.leftAmt = leftAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tlj_audit.emp_id
     *
     * @return the value of tlj_audit.emp_id
     *
     * @mbggenerated
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tlj_audit.emp_id
     *
     * @param empId the value for tlj_audit.emp_id
     *
     * @mbggenerated
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tlj_audit.emp_username
     *
     * @return the value of tlj_audit.emp_username
     *
     * @mbggenerated
     */
    public String getEmpUsername() {
        return empUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tlj_audit.emp_username
     *
     * @param empUsername the value for tlj_audit.emp_username
     *
     * @mbggenerated
     */
    public void setEmpUsername(String empUsername) {
        this.empUsername = empUsername == null ? null : empUsername.trim();
    }

    public Date getCreatedTime() {
        return createdTime;
    }

    public Integer getMinAmt() {
        return minAmt;
    }

    public void setMinAmt(Integer minAmt) {
        this.minAmt = minAmt;
    }

    public Integer getMaxAmt() {
        return maxAmt;
    }

    public void setMaxAmt(Integer maxAmt) {
        this.maxAmt = maxAmt;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}