package com.fh.taolijie.domain.acc;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.math.BigDecimal;
import java.util.Date;

@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class CashAccModel {
    private Integer id;

    private String alipayAcc;

    private String bankAcc;

    private BigDecimal availableBalance;

    private BigDecimal frozenBalance;

    private BigDecimal totalBalance;

    private String status;

    private Date updateTime;

    private Date createdTime;

    private Integer memberId;

    private String username;

    private String memberRole;

    private String dealPassword;

    private String phoneNumber;

    private String email;

    private String name;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAlipayAcc() {
        return alipayAcc;
    }

    public void setAlipayAcc(String alipayAcc) {
        this.alipayAcc = alipayAcc;
    }

    public String getBankAcc() {
        return bankAcc;
    }

    public void setBankAcc(String bankAcc) {
        this.bankAcc = bankAcc;
    }

    public BigDecimal getAvailableBalance() {
        return availableBalance;
    }

    public void setAvailableBalance(BigDecimal availableBalance) {
        this.availableBalance = availableBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_acc.frozen_balance
     *
     * @return the value of cash_acc.frozen_balance
     *
     * @mbggenerated
     */
    public BigDecimal getFrozenBalance() {
        return frozenBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_acc.frozen_balance
     *
     * @param frozenBalance the value for cash_acc.frozen_balance
     *
     * @mbggenerated
     */
    public void setFrozenBalance(BigDecimal frozenBalance) {
        this.frozenBalance = frozenBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_acc.total_balance
     *
     * @return the value of cash_acc.total_balance
     *
     * @mbggenerated
     */
    public BigDecimal getTotalBalance() {
        return totalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_acc.total_balance
     *
     * @param totalBalance the value for cash_acc.total_balance
     *
     * @mbggenerated
     */
    public void setTotalBalance(BigDecimal totalBalance) {
        this.totalBalance = totalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_acc.status
     *
     * @return the value of cash_acc.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_acc.status
     *
     * @param status the value for cash_acc.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_acc.update_time
     *
     * @return the value of cash_acc.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_acc.update_time
     *
     * @param updateTime the value for cash_acc.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_acc.member_id
     *
     * @return the value of cash_acc.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_acc.member_id
     *
     * @param memberId the value for cash_acc.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_acc.username
     *
     * @return the value of cash_acc.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_acc.username
     *
     * @param username the value for cash_acc.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_acc.member_role
     *
     * @return the value of cash_acc.member_role
     *
     * @mbggenerated
     */
    public String getMemberRole() {
        return memberRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_acc.member_role
     *
     * @param memberRole the value for cash_acc.member_role
     *
     * @mbggenerated
     */
    public void setMemberRole(String memberRole) {
        this.memberRole = memberRole == null ? null : memberRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_acc.deal_password
     *
     * @return the value of cash_acc.deal_password
     *
     * @mbggenerated
     */
    public String getDealPassword() {
        return dealPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_acc.deal_password
     *
     * @param dealPassword the value for cash_acc.deal_password
     *
     * @mbggenerated
     */
    public void setDealPassword(String dealPassword) {
        this.dealPassword = dealPassword == null ? null : dealPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_acc.phone_number
     *
     * @return the value of cash_acc.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_acc.phone_number
     *
     * @param phoneNumber the value for cash_acc.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_acc.email
     *
     * @return the value of cash_acc.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_acc.email
     *
     * @param email the value for cash_acc.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public Date getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_acc.name
     *
     * @return the value of cash_acc.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_acc.name
     *
     * @param name the value for cash_acc.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}