-- MySQL Script generated by MySQL Workbench
-- 2015年03月05日 星期四 17时16分19秒
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema taolijie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taolijie` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `taolijie` ;

-- -----------------------------------------------------
-- Table `taolijie`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`role` (
  `rid` INT NOT NULL AUTO_INCREMENT,
  `rolename` VARCHAR(45) NULL,
  `memo` TEXT NULL,
  PRIMARY KEY (`rid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL COMMENT '登陆名',
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL COMMENT '真人人名',
  `student_id` VARCHAR(45) NULL COMMENT '学号',
  `gender` VARCHAR(10) NULL,
  `verified` VARCHAR(50) NULL COMMENT '审核状态：NONE, INPROCESS, VERIFIED',
  `profile_photo_path` VARCHAR(256) NULL COMMENT '头像路径',
  `phone` VARCHAR(20) NULL,
  `qq` VARCHAR(2) NULL,
  `age` INT NULL,
  `company_name` VARCHAR(128) NULL,
  `block_list` TEXT NULL COMMENT '要屏蔽的商家。保存id号，以;分隔。如1;2;3;4;5',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`job_post_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`job_post_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `memo` TEXT NULL,
  `level` INT NULL COMMENT '分类层次：一级分类(1)、二级分类(2)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '兼职信息分类';


-- -----------------------------------------------------
-- Table `taolijie`.`job_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`job_post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `expired_time` DATE NULL,
  `post_time` DATE NULL,
  `work_place` VARCHAR(45) NULL,
  `wage` DECIMAL(6,1) NULL,
  `time_to_pay` VARCHAR(45) NULL COMMENT '结算方式',
  `job_description` VARCHAR(45) NULL COMMENT '工作简介',
  `contact` VARCHAR(45) NULL COMMENT '联系人名',
  `contact_phone` VARCHAR(45) NULL COMMENT '联系人手机号',
  `contact_email` VARCHAR(45) NULL COMMENT '联系�' /* comment truncated */ /*�mail
*/,
  `contact_qq` VARCHAR(45) NULL,
  `job_detail` VARCHAR(45) NULL COMMENT '工作详细描述',
  `introduce` TEXT NULL COMMENT '商家介绍',
  `likes` INT NULL,
  `dislikes` INT NULL,
  `job_post_category_id` INT NULL,
  `member_id` INT NULL,
  `education_level` VARCHAR(45) NULL COMMENT '学历要求信息',
  PRIMARY KEY (`id`),
  INDEX `fk_job_post_job_post_category1_idx` (`job_post_category_id` ASC),
  INDEX `fk_job_post_member1_idx` (`member_id` ASC),
  CONSTRAINT `fk_job_post_job_post_category1`
    FOREIGN KEY (`job_post_category_id`)
    REFERENCES `taolijie`.`job_post_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_post_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `taolijie`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`resume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`resume` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `gender` VARCHAR(10) NULL,
  `age` INT NULL,
  `height` INT NULL,
  `phone_path` VARCHAR(256) NULL COMMENT '用户头像图片路径',
  `email` VARCHAR(45) NULL,
  `qq` VARCHAR(45) NULL,
  `experience` TEXT NULL,
  `introduce` TEXT NULL COMMENT '自我介绍',
  `member_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Resume_User1_idx` (`member_id` ASC),
  CONSTRAINT `fk_Resume_User1`
    FOREIGN KEY (`member_id`)
    REFERENCES `taolijie`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `post_id` INT NULL,
  `member_id` INT NULL,
  `time` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Review_Info1_idx` (`post_id` ASC),
  INDEX `fk_Review_User1_idx` (`member_id` ASC),
  CONSTRAINT `fk_Review_Info1`
    FOREIGN KEY (`post_id`)
    REFERENCES `taolijie`.`job_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_User1`
    FOREIGN KEY (`member_id`)
    REFERENCES `taolijie`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`school` (
  `id` INT NOT NULL,
  `short_name` VARCHAR(20) NULL,
  `full_name` VARCHAR(128) NULL,
  `province` VARCHAR(45) NULL COMMENT '大学所在省份',
  `type` VARCHAR(45) NULL COMMENT 'e.g., HIGH_SCHOOL, UNDERGRADUATE, INSTITUTE(专科)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`academy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`academy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `short_name` VARCHAR(20) NULL,
  `full_name` VARCHAR(128) NULL,
  `college_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_School_College1_idx` (`college_id` ASC),
  CONSTRAINT `fk_School_College1`
    FOREIGN KEY (`college_id`)
    REFERENCES `taolijie`.`school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '学院';


-- -----------------------------------------------------
-- Table `taolijie`.`banner_pic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`banner_pic` (
  `id` INT NOT NULL,
  `picture_path` VARCHAR(45) NULL,
  `time` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`second_hand_post_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`second_hand_post_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `memo` TEXT NULL,
  `level` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '二手信息帖子分类';


-- -----------------------------------------------------
-- Table `taolijie`.`second_hand_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`second_hand_post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `expired_time` DATE NULL COMMENT '过期时间',
  `post_time` DATE NULL,
  `depreciation_rate` VARCHAR(10) NULL COMMENT '9成�' /* comment truncated */ /*95成
*/,
  `original_price` DECIMAL(6,1) NULL COMMENT '原价格',
  `sell_price` DECIMAL(6,1) NULL COMMENT '现价',
  `picture_path` TEXT NULL COMMENT '物品图片路径，以;分号分隔。如: /home/a.jpg;/home/b.jpg',
  `description` TEXT NULL COMMENT '物品描述',
  `likes` INT NULL,
  `dislikes` INT NULL,
  `member_id` INT NULL,
  `second_hand_post_category_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_second_hand_post_member1_idx` (`member_id` ASC),
  INDEX `fk_second_hand_post_second_hand_post_category1_idx` (`second_hand_post_category_id` ASC),
  CONSTRAINT `fk_second_hand_post_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `taolijie`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_second_hand_post_second_hand_post_category1`
    FOREIGN KEY (`second_hand_post_category_id`)
    REFERENCES `taolijie`.`second_hand_post_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NULL,
  `title` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `is_read` INT NULL COMMENT '0:未读, 1已读',
  `time` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notification_member1_idx` (`member_id` ASC),
  CONSTRAINT `fk_notification_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `taolijie`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`job_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`job_post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `expired_time` DATE NULL,
  `post_time` DATE NULL,
  `work_place` VARCHAR(45) NULL,
  `wage` DECIMAL(6,1) NULL,
  `time_to_pay` VARCHAR(45) NULL COMMENT '结算方式',
  `job_description` VARCHAR(45) NULL COMMENT '工作简介',
  `contact` VARCHAR(45) NULL COMMENT '联系人名',
  `contact_phone` VARCHAR(45) NULL COMMENT '联系人手机号',
  `contact_email` VARCHAR(45) NULL COMMENT '联系�' /* comment truncated */ /*�mail
*/,
  `contact_qq` VARCHAR(45) NULL,
  `job_detail` VARCHAR(45) NULL COMMENT '工作详细描述',
  `introduce` TEXT NULL COMMENT '商家介绍',
  `likes` INT NULL,
  `dislikes` INT NULL,
  `job_post_category_id` INT NULL,
  `member_id` INT NULL,
  `education_level` VARCHAR(45) NULL COMMENT '学历要求信息',
  PRIMARY KEY (`id`),
  INDEX `fk_job_post_job_post_category1_idx` (`job_post_category_id` ASC),
  INDEX `fk_job_post_member1_idx` (`member_id` ASC),
  CONSTRAINT `fk_job_post_job_post_category1`
    FOREIGN KEY (`job_post_category_id`)
    REFERENCES `taolijie`.`job_post_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_post_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `taolijie`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `picture_path` TEXT NULL COMMENT '文章引用的图片路径，以;分隔',
  `time` DATE NULL,
  `member_id` INT NULL,
  `head_picture_path` VARCHAR(256) NULL COMMENT '文章标题旁边显示的图片',
  PRIMARY KEY (`id`),
  INDEX `fk_news_member1_idx` (`member_id` ASC),
  CONSTRAINT `fk_news_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `taolijie`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '首页显示的新闻信息';


-- -----------------------------------------------------
-- Table `taolijie`.`education_experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`education_experience` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NULL,
  `college_id` INT NULL,
  `admission_time` DATE NULL COMMENT '入学时间',
  `length_of_schooling` INT NULL COMMENT '学制(年)',
  `major` VARCHAR(45) NULL COMMENT '专业',
  `academy_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_education_experience_member1_idx` (`member_id` ASC),
  INDEX `fk_education_experience_college1_idx` (`college_id` ASC),
  INDEX `fk_education_experience_academy1_idx` (`academy_id` ASC),
  CONSTRAINT `fk_education_experience_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `taolijie`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_education_experience_college1`
    FOREIGN KEY (`college_id`)
    REFERENCES `taolijie`.`school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_education_experience_academy1`
    FOREIGN KEY (`academy_id`)
    REFERENCES `taolijie`.`academy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '教育经历';


-- -----------------------------------------------------
-- Table `taolijie`.`member_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`member_role` (
  `member_id` INT NULL,
  `role_rid` INT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_member_has_role_role1_idx` (`role_rid` ASC),
  INDEX `fk_member_has_role_member1_idx` (`member_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_member_has_role_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `taolijie`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_has_role_role1`
    FOREIGN KEY (`role_rid`)
    REFERENCES `taolijie`.`role` (`rid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`application_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taolijie`.`application_config` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
