-- MySQL Script generated by MySQL Workbench
-- Fri Oct 30 22:07:43 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema taolijie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taolijie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taolijie` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `taolijie` ;

-- -----------------------------------------------------
-- Table `taolijie`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`role` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`role` (
  `rid` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `rolename` VARCHAR(45) NULL COMMENT '',
  `memo` TEXT NULL COMMENT '',
  PRIMARY KEY (`rid`)  COMMENT '',
  INDEX `idx_rid` (`rid` ASC)  COMMENT '',
  INDEX `idx_rolename` (`rolename` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`member` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`member` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '登陆名',
  `reg_type` INT NULL COMMENT '注册类型. 0: 用户名注册 1:手机号注册 2: 邮箱注册',
  `password` VARCHAR(90) NOT NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '真人人名',
  `student_id` TEXT NULL COMMENT '学号',
  `qq` VARCHAR(20) NULL COMMENT '',
  `age` INT NULL COMMENT '',
  `gender` VARCHAR(10) NULL COMMENT '',
  `credits` INT NULL DEFAULT 0 COMMENT '积分',
  `auto_login_identifier` VARCHAR(60) NULL COMMENT '',
  `app_token` VARCHAR(25) NULL COMMENT '移动端的登陆标识',
  `wechat_token` VARCHAR(20) NULL COMMENT '微信登陆token',
  `last_post_time` DATETIME NULL COMMENT '最近一次发布信息的时间',
  `reset_password_token` VARCHAR(45) NULL COMMENT '',
  `created_time` DATETIME NULL COMMENT '',
  `verified` VARCHAR(3) NULL DEFAULT '00' COMMENT '00: 未审核 01: 等待审核 02: 已通过 03:审核失败',
  `profile_photo_path` VARCHAR(256) NULL COMMENT '头像路径',
  `phone` VARCHAR(20) NULL COMMENT '',
  `company_name` VARCHAR(128) NULL COMMENT '',
  `block_list` TEXT NULL COMMENT '要屏蔽的商家。保存id号，以;分隔。如1;2;3;4;5',
  `valid` TINYINT(1) NULL DEFAULT 1 COMMENT '是否封号',
  `complaint` INT NULL DEFAULT 0 COMMENT '被投诉数',
  `applied_job_ids` TEXT NULL COMMENT '已申请的工作id',
  `profile_photo_id` INT NULL COMMENT '',
  `last_token_date` DATETIME NULL COMMENT '',
  `school_organization` VARCHAR(15) NULL COMMENT '校园组织验证状态. NONE, IN_PROCESS, REJECTED, PASSED',
  `liked_job_ids` TEXT NULL COMMENT '',
  `liked_sh_ids` TEXT NULL COMMENT '',
  `read_global_noti_ids` TEXT NULL COMMENT '已经读过的全局通知',
  `last_job_date` DATETIME NULL COMMENT '最近一次发布兼职信息的时间',
  `last_sh_date` DATETIME NULL COMMENT '最近一次发布二手信息的时间',
  `user_level` VARCHAR(10) NULL COMMENT '',
  `province` VARCHAR(30) NULL COMMENT '',
  `city` VARCHAR(30) NULL COMMENT '',
  `region` VARCHAR(30) NULL COMMENT '',
  `college_name` VARCHAR(45) NULL COMMENT '',
  `major` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_member_app_token` (`app_token` ASC)  COMMENT '',
  INDEX `idx_member_username` (`username` ASC)  COMMENT '',
  INDEX `idx_member_auto_login_identifer` (`auto_login_identifier` ASC)  COMMENT '',
  INDEX `idx_reg_type` (`reg_type` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`job_post_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`job_post_category` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`job_post_category` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `memo` TEXT NULL COMMENT '',
  `level` INT NULL COMMENT '分类层次：一级分类(1)、二级分类(2)',
  `theme_color` VARCHAR(45) NULL COMMENT '#FFFFFF值',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_job_category_name` (`name` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '兼职信息分类';


-- -----------------------------------------------------
-- Table `taolijie`.`job_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`job_post` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`job_post` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NULL COMMENT '',
  `expired_time` DATETIME NULL COMMENT '',
  `post_time` DATETIME NULL COMMENT '',
  `flush_time` DATETIME NOT NULL COMMENT '',
  `work_place` VARCHAR(256) NULL COMMENT '',
  `wage` DECIMAL(6,1) NULL COMMENT '',
  `time_to_pay` VARCHAR(45) NULL COMMENT '结算方式',
  `job_description` VARCHAR(1000) NULL COMMENT '工作简介',
  `contact` VARCHAR(45) NULL COMMENT '联系人名',
  `contact_phone` VARCHAR(45) NULL COMMENT '联系人手机号',
  `contact_email` VARCHAR(45) NULL COMMENT '联系人mail\n',
  `contact_qq` VARCHAR(45) NULL COMMENT '',
  `job_detail` VARCHAR(1000) NULL COMMENT '工作详细描述',
  `introduce` TEXT NULL COMMENT '商家介绍',
  `likes` INT NULL DEFAULT 0 COMMENT '',
  `dislikes` INT NULL DEFAULT 0 COMMENT '',
  `job_post_category_id` INT NULL COMMENT '',
  `member_id` INT NULL COMMENT '',
  `education_level` VARCHAR(45) NULL COMMENT '学历要求信息',
  `complaint` INT NULL DEFAULT 0 COMMENT '',
  `work_time` VARCHAR(128) NULL COMMENT '工作时间',
  `salary_unit` VARCHAR(45) NULL COMMENT '工资单位：天、周、月',
  `page_view` INT NULL DEFAULT 0 COMMENT '',
  `verified` VARCHAR(45) NULL COMMENT '',
  `job_postcol` VARCHAR(45) NULL COMMENT '',
  `application_resume_ids` TEXT NULL COMMENT '收到的简历id',
  `applicant_amount` INT NULL DEFAULT 0 COMMENT '申请者数量',
  `deleted` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `work_region` VARCHAR(45) NULL COMMENT '工作的地域，如博山、张店等等',
  `expired` TINYINT(1) NULL DEFAULT 0 COMMENT '是否过期',
  `province` VARCHAR(15) NULL COMMENT '工作所在省',
  `city` VARCHAR(15) NULL COMMENT '工作所在市',
  `region` VARCHAR(15) NULL COMMENT '工作所在区',
  `is_indexed` TINYINT(1) NULL DEFAULT 0 COMMENT '是否已经完成了inverted index的创建',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_is_indexed` (`is_indexed` ASC)  COMMENT '',
  INDEX `idx_job_title` (`title` ASC)  COMMENT '',
  INDEX `idx_deleted` (`deleted` ASC)  COMMENT '',
  INDEX `idx_post_time` (`post_time` ASC)  COMMENT '',
  INDEX `idx_flush_time` (`flush_time` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '兼职表';


-- -----------------------------------------------------
-- Table `taolijie`.`resume`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`resume` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`resume` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `gender` VARCHAR(10) NULL COMMENT '',
  `age` INT NULL COMMENT '',
  `height` INT NULL COMMENT '',
  `photo_path` VARCHAR(256) NULL COMMENT '用户头像图片路径',
  `email` VARCHAR(45) NULL COMMENT '',
  `qq` VARCHAR(45) NULL COMMENT '',
  `experience` TEXT NULL COMMENT '',
  `introduce` TEXT NULL COMMENT '自我介绍',
  `member_id` INT NULL COMMENT '',
  `access_authority` VARCHAR(45) NULL COMMENT '访问权限: ME_ONLY, ALL',
  `page_view` INT NULL DEFAULT 0 COMMENT '访问量',
  `verified` VARCHAR(45) NULL COMMENT '审核状态',
  `photo_id` INT NULL COMMENT '',
  `phone_number` VARCHAR(45) NULL COMMENT '',
  `wechat_account` VARCHAR(45) NULL COMMENT '',
  `created_time` DATETIME NULL COMMENT '',
  `spare_time` VARCHAR(45) NULL COMMENT '空闲时间描述',
  `major` VARCHAR(30) NULL COMMENT '专业',
  `school` VARCHAR(30) NULL COMMENT '学校名',
  `preferred_province` VARCHAR(30) NULL COMMENT '',
  `preferred_city` VARCHAR(30) NULL COMMENT '',
  `preferred_region` VARCHAR(30) NULL COMMENT '',
  `birthday` DATETIME NULL COMMENT 'ß',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_member_id` (`member_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`review` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `content` TEXT NULL COMMENT '',
  `job_post_id` INT NULL COMMENT '如果被评论者是兼职，该字段为兼职id',
  `member_id` INT NULL COMMENT '',
  `time` DATETIME NULL COMMENT '',
  `replied_review_id` INT NULL COMMENT '此field有值表示这是一条评论回复',
  `sh_post_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_sh_post_id` (`sh_post_id` ASC)  COMMENT '',
  INDEX `idx_replied_review_id` (`replied_review_id` ASC)  COMMENT '',
  INDEX `idx_job_post_id` (`job_post_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`banner_pic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`banner_pic` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`banner_pic` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `created_time` DATETIME NULL COMMENT '',
  `picture_id` INT NULL COMMENT 'image_resource表的主键',
  `url` VARCHAR(256) NULL COMMENT '',
  `memo` VARCHAR(256) NULL COMMENT '',
  `order_index` INT NULL COMMENT '排序,值越小越靠前',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`second_hand_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`second_hand_post` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`second_hand_post` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NULL COMMENT '',
  `expired_time` DATETIME NULL COMMENT '过期时间',
  `post_time` DATETIME NULL COMMENT '',
  `depreciation_rate` VARCHAR(10) NULL COMMENT '9成，95成\n',
  `original_price` DECIMAL(6,1) NULL COMMENT '原价格',
  `sell_price` DECIMAL(6,1) NULL COMMENT '现价',
  `picture_path` TEXT NULL COMMENT '物品图片路径，以;分号分隔。如: /home/a.jpg;/home/b.jpg',
  `description` TEXT NULL COMMENT '物品描述',
  `likes` INT NULL DEFAULT 0 COMMENT '',
  `dislikes` INT NULL DEFAULT 0 COMMENT '',
  `member_id` INT NULL COMMENT '',
  `second_hand_post_category_id` INT NULL COMMENT '',
  `complaint` INT NULL DEFAULT 0 COMMENT '',
  `page_view` INT NULL DEFAULT 0 COMMENT '',
  `verified` VARCHAR(45) NULL COMMENT '',
  `trade_place` VARCHAR(45) NULL COMMENT '',
  `deleted` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `contact_name` VARCHAR(20) NULL COMMENT '',
  `contact_qq` VARCHAR(20) NULL COMMENT '',
  `contact_phone` VARCHAR(20) NULL COMMENT '',
  `expired` TINYINT(1) NULL DEFAULT 0 COMMENT '是否下架',
  `is_indexed` TINYINT(1) NULL DEFAULT 0 COMMENT '是否已经完成了inverted index的创建',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_is_indexed` (`is_indexed` ASC)  COMMENT '',
  INDEX `dix_sh_title` (`title` ASC)  COMMENT '',
  INDEX `idx_member_id` (`member_id` ASC)  COMMENT '',
  INDEX `idx_deleted` (`is_indexed` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`second_hand_post_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`second_hand_post_category` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`second_hand_post_category` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `memo` TEXT NULL COMMENT '',
  `level` INT NULL COMMENT '',
  `theme_color` VARCHAR(45) NULL COMMENT '#FFAABB值',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_sh_category_name` (`name` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '二手信息帖子分类';


-- -----------------------------------------------------
-- Table `taolijie`.`private_notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`private_notification` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`private_notification` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `member_id` INT NULL COMMENT '',
  `title` VARCHAR(45) NULL COMMENT '',
  `content` TEXT NULL COMMENT '',
  `is_read` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `time` DATETIME NULL COMMENT '',
  `access_range` VARCHAR(45) NULL COMMENT 'GLOBAL, (与role_type相同)',
  `to_member_id` INT NULL COMMENT '',
  `noti_type` VARCHAR(2) NULL COMMENT '	⁃	通知的类型。0为管理员发送的通知, 1为程序自动生成的通知(如被评论), 2为普通用户发送的通知\n',
  `post_id` INT NULL COMMENT '',
  `post_type` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_noti_member_is_read_type` (`member_id` ASC, `is_read` ASC, `noti_type` ASC)  COMMENT '',
  INDEX `idx_member_id_type` (`member_id` ASC, `noti_type` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`job_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`job_post` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`job_post` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NULL COMMENT '',
  `expired_time` DATETIME NULL COMMENT '',
  `post_time` DATETIME NULL COMMENT '',
  `flush_time` DATETIME NOT NULL COMMENT '',
  `work_place` VARCHAR(256) NULL COMMENT '',
  `wage` DECIMAL(6,1) NULL COMMENT '',
  `time_to_pay` VARCHAR(45) NULL COMMENT '结算方式',
  `job_description` VARCHAR(1000) NULL COMMENT '工作简介',
  `contact` VARCHAR(45) NULL COMMENT '联系人名',
  `contact_phone` VARCHAR(45) NULL COMMENT '联系人手机号',
  `contact_email` VARCHAR(45) NULL COMMENT '联系人mail\n',
  `contact_qq` VARCHAR(45) NULL COMMENT '',
  `job_detail` VARCHAR(1000) NULL COMMENT '工作详细描述',
  `introduce` TEXT NULL COMMENT '商家介绍',
  `likes` INT NULL DEFAULT 0 COMMENT '',
  `dislikes` INT NULL DEFAULT 0 COMMENT '',
  `job_post_category_id` INT NULL COMMENT '',
  `member_id` INT NULL COMMENT '',
  `education_level` VARCHAR(45) NULL COMMENT '学历要求信息',
  `complaint` INT NULL DEFAULT 0 COMMENT '',
  `work_time` VARCHAR(128) NULL COMMENT '工作时间',
  `salary_unit` VARCHAR(45) NULL COMMENT '工资单位：天、周、月',
  `page_view` INT NULL DEFAULT 0 COMMENT '',
  `verified` VARCHAR(45) NULL COMMENT '',
  `job_postcol` VARCHAR(45) NULL COMMENT '',
  `application_resume_ids` TEXT NULL COMMENT '收到的简历id',
  `applicant_amount` INT NULL DEFAULT 0 COMMENT '申请者数量',
  `deleted` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `work_region` VARCHAR(45) NULL COMMENT '工作的地域，如博山、张店等等',
  `expired` TINYINT(1) NULL DEFAULT 0 COMMENT '是否过期',
  `province` VARCHAR(15) NULL COMMENT '工作所在省',
  `city` VARCHAR(15) NULL COMMENT '工作所在市',
  `region` VARCHAR(15) NULL COMMENT '工作所在区',
  `is_indexed` TINYINT(1) NULL DEFAULT 0 COMMENT '是否已经完成了inverted index的创建',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_is_indexed` (`is_indexed` ASC)  COMMENT '',
  INDEX `idx_job_title` (`title` ASC)  COMMENT '',
  INDEX `idx_deleted` (`deleted` ASC)  COMMENT '',
  INDEX `idx_post_time` (`post_time` ASC)  COMMENT '',
  INDEX `idx_flush_time` (`flush_time` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '兼职表';


-- -----------------------------------------------------
-- Table `taolijie`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`news` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NULL COMMENT '',
  `content` TEXT NULL COMMENT '',
  `place` VARCHAR(45) NULL COMMENT '活动地点',
  `picture_path` TEXT NULL COMMENT '文章引用的图片路径，以;分隔',
  `time` DATETIME NULL COMMENT '',
  `member_id` INT NULL COMMENT '',
  `head_picture_path` VARCHAR(256) NULL COMMENT '文章标题旁边显示的图片',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_time` (`time` ASC)  COMMENT '',
  INDEX `idx_member_id` (`member_id` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '首页显示的新闻信息';


-- -----------------------------------------------------
-- Table `taolijie`.`member_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`member_role` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`member_role` (
  `member_id` INT NULL COMMENT '',
  `role_rid` INT NULL COMMENT '',
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_role_rid` (`role_rid` ASC)  COMMENT '',
  INDEX `idx_member_id` (`member_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`image_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`image_resource` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`image_resource` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `file_name` VARCHAR(256) NULL COMMENT '',
  `extension` VARCHAR(10) NULL COMMENT '.jpeg, .gif',
  `bin_data` MEDIUMBLOB NULL COMMENT '',
  `type` VARCHAR(45) NULL COMMENT '图片的作用. 如:身份证图片, 证件图片等',
  `member_id` INT NULL COMMENT '如果是用户上传的证件照, 则这里为用户表的id',
  `job_post_id` INT NULL COMMENT '',
  `sh_post_id` INT NULL COMMENT '',
  `news_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`bulletin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`bulletin` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`bulletin` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `content` TEXT NULL COMMENT '',
  `created_time` DATE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '系统公告';


-- -----------------------------------------------------
-- Table `taolijie`.`resume_job_post_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`resume_job_post_category` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`resume_job_post_category` (
  `resume_id` INT NULL COMMENT '',
  `job_post_category_id` INT NULL COMMENT '',
  INDEX `idx_resume_id` (`resume_id` ASC)  COMMENT '',
  INDEX `idx_job_post_category` (`job_post_category_id` ASC)  COMMENT '',
  INDEX `idx_resume_id_and_job_post_category` (`resume_id` ASC, `job_post_category_id` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '求职意向关联表';


-- -----------------------------------------------------
-- Table `taolijie`.`taoli_ivy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`taoli_ivy` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`taoli_ivy` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NULL COMMENT '',
  `content` TEXT NULL COMMENT '',
  `created_time` DATE NULL COMMENT '',
  `likes` INT NULL COMMENT '',
  `expired_time` DATE NULL COMMENT '过期时间',
  `taoli_ivy_category_id` INT NULL COMMENT '',
  `member_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '桃李青藤';


-- -----------------------------------------------------
-- Table `taolijie`.`taoli_ivy_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`taoli_ivy_category` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`taoli_ivy_category` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `memo` TEXT NULL COMMENT '',
  `level` INT NULL COMMENT '',
  `theme_color` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '桃李青藤分类表';


-- -----------------------------------------------------
-- Table `taolijie`.`school_organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`school_organization` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`school_organization` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(100) NULL COMMENT '简介',
  `member_names` TEXT NULL COMMENT '成员列表',
  `slogan` VARCHAR(100) NULL COMMENT '口号',
  `bulletin` TEXT NULL COMMENT '公告',
  `location` VARCHAR(45) NULL COMMENT '地点',
  `qq` VARCHAR(45) NULL COMMENT '',
  `phone` VARCHAR(45) NULL COMMENT '',
  `wechat` VARCHAR(45) NULL COMMENT '',
  `member_id` INT NULL COMMENT '',
  `school_organization_category_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '校内组织';


-- -----------------------------------------------------
-- Table `taolijie`.`school_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`school_activity` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`school_activity` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `member_id` INT NULL COMMENT '如果是个人发布的, 该字段存放用户id',
  `school_organization_id` INT NULL COMMENT '',
  `title` VARCHAR(45) NULL COMMENT '',
  `content` TEXT NULL COMMENT '',
  `created_time` DATE NULL COMMENT '',
  `expired_time` DATE NULL COMMENT '',
  `likes` INT NULL COMMENT '',
  `school_activity_category_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '校园活动';


-- -----------------------------------------------------
-- Table `taolijie`.`ivy_activity_image_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`ivy_activity_image_resource` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`ivy_activity_image_resource` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `file_name` VARCHAR(256) NULL COMMENT '',
  `extension` VARCHAR(10) NULL COMMENT '',
  `bin_data` MEDIUMBLOB NULL COMMENT '',
  `ivy_id` INT NULL COMMENT '',
  `activity_id` INT NULL COMMENT '',
  `type` VARCHAR(45) NULL COMMENT 'MAIN: 主要图片',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '桃李青藤, 校园活动中使用到的图片信息';


-- -----------------------------------------------------
-- Table `taolijie`.`member_verification_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`member_verification_rel` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`member_verification_rel` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `member_id` INT NULL COMMENT '',
  `image_id` INT NULL COMMENT '',
  `image_type` VARCHAR(45) NULL COMMENT 'ID_FRONT, ID_BACK, ORG_FRONT, ORG_BACK, STU_ID_FRONT, STU_ID_BACK',
  `created_time` DATE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '与image_resource表关联, 保存用户上传的证件照片';


-- -----------------------------------------------------
-- Table `taolijie`.`school_organization_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`school_organization_category` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`school_organization_category` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `memo` TEXT NULL COMMENT '',
  `level` INT NULL COMMENT '',
  `theme_color` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '校园组织分类表';


-- -----------------------------------------------------
-- Table `taolijie`.`participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`participant` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`participant` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `member_id` INT NULL COMMENT '',
  `ivy_id` INT NULL COMMENT '',
  `activity_id` INT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `academy` VARCHAR(45) NULL COMMENT '学院',
  `className` VARCHAR(45) NULL COMMENT '班级',
  `qq` VARCHAR(45) NULL COMMENT '',
  `phone` VARCHAR(45) NULL COMMENT '',
  `weichat` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `gender` VARCHAR(10) NULL COMMENT '',
  `created_time` DATE NULL COMMENT '报名时间',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '\"想去\"功能对应的数据表';


-- -----------------------------------------------------
-- Table `taolijie`.`credits_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`credits_level` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`credits_level` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `min_credits` INT NULL COMMENT '',
  `max_credits` INT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `memo` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '积分阶梯';


-- -----------------------------------------------------
-- Table `taolijie`.`school_activity_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`school_activity_category` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`school_activity_category` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `memo` TEXT NULL COMMENT '',
  `level` INT NULL COMMENT '',
  `theme_color` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`resume_post_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`resume_post_rel` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`resume_post_rel` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `resume_id` INT NULL COMMENT '',
  `job_post_id` INT NULL COMMENT '',
  `created_time` DATETIME NULL COMMENT '投递时间',
  `member_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '简历投递表';


-- -----------------------------------------------------
-- Table `taolijie`.`system_notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`system_notification` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`system_notification` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NULL COMMENT '',
  `content` TEXT NULL COMMENT '',
  `is_read` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `time` DATETIME NULL COMMENT '',
  `access_range` VARCHAR(45) NULL COMMENT 'GLOBAL, (与role_type相同)',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_noti_acc_range` (`access_range` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`recommended_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`recommended_post` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`recommended_post` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `job_id` INT NULL COMMENT '',
  `sh_id` INT NULL COMMENT '',
  `resume_id` INT NULL COMMENT '',
  `quest_id` INT NULL COMMENT '',
  `apply_time` DATETIME NULL COMMENT '申请时间',
  `validation` TINYINT(1) NULL DEFAULT 0 COMMENT '是否显示在首页',
  `member_id` INT NULL COMMENT '申请人',
  `memo` VARCHAR(300) NULL COMMENT '',
  `order_index` INT NULL COMMENT '排序指数，值越小越靠前，从0开始',
  `pass_time` DATETIME NULL COMMENT '通过审核的时间',
  `remove_time` DATETIME NULL COMMENT '下架时间',
  `post_title` VARCHAR(45) NULL COMMENT '冗余字段，与帖子表的title值相同',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_reco_job` (`job_id` ASC)  COMMENT '',
  INDEX `idx_reco_sh` (`sh_id` ASC)  COMMENT '',
  INDEX `idx_reco_resume` (`resume_id` ASC)  COMMENT '',
  INDEX `idx_reco_validation` (`validation` ASC)  COMMENT '',
  INDEX `idx_reco_member` (`member_id` ASC)  COMMENT '',
  INDEX `idx_reco_order` (`order_index` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`feedback` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`feedback` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '反馈表',
  `phone` VARCHAR(20) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `created_time` TIMESTAMP NULL COMMENT '',
  `title` VARCHAR(30) NULL COMMENT '',
  `content` VARCHAR(500) NULL COMMENT '',
  `member_id` INT NULL COMMENT '反馈者的用户id. 如果没有则留空',
  `username` VARCHAR(45) NULL COMMENT '冗余字段，保存member表的用户名',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_member_id` (`member_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`my_collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`my_collection` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`my_collection` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `created_time` DATETIME NULL COMMENT '收藏时间',
  `member_id` INT NULL COMMENT '收藏者用户id',
  `job_post_id` INT NULL COMMENT '',
  `sh_post_id` INT NULL COMMENT '',
  `resume_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_collection_job_post` (`job_post_id` ASC)  COMMENT '',
  INDEX `idx_collection_sh_post` (`sh_post_id` ASC)  COMMENT '',
  INDEX `idx_collection_resume` (`resume_id` ASC)  COMMENT '',
  INDEX `idx_collection_mem_job` (`member_id` ASC, `job_post_id` ASC)  COMMENT '',
  INDEX `idx_collection_mem_sh` (`member_id` ASC, `sh_post_id` ASC)  COMMENT '',
  INDEX `idx_collection_mem_resume` (`resume_id` ASC, `member_id` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '我的收藏关联表';


-- -----------------------------------------------------
-- Table `taolijie`.`quest_cate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`quest_cate` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`quest_cate` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(20) NULL COMMENT '分类名',
  `memo` VARCHAR(200) NULL COMMENT '',
  `theme_color` VARCHAR(10) NULL COMMENT '',
  `level` INT NULL COMMENT '层级',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_name` (`name` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '轻兼职分类表';


-- -----------------------------------------------------
-- Table `taolijie`.`quest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`quest` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`quest` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `coupon` TINYINT(1) NULL DEFAULT 0 COMMENT '有无卡券',
  `coupon_left` INT NULL DEFAULT 0 COMMENT '卡券剩余数量',
  `title` VARCHAR(20) NULL COMMENT '',
  `member_id` INT NOT NULL COMMENT '发布者id',
  `created_time` DATETIME NOT NULL COMMENT '',
  `flush_time` DATETIME NOT NULL COMMENT '',
  `tag_expire_time` DATETIME NULL COMMENT '标签过期时间',
  `quest_cate_id` INT NOT NULL COMMENT '任务分类',
  `start_time` DATETIME NULL COMMENT '',
  `end_time` DATETIME NULL COMMENT '',
  `limit_time` INT NULL DEFAULT 2 COMMENT '做任务的时间限制，单位为小时',
  `total_amt` INT NOT NULL COMMENT '任务总数量',
  `left_amt` INT NULL COMMENT '任务剩余数量',
  `emp_status` INT NOT NULL COMMENT '商家在我的发布中看到的状态值. 0: 未发布 1:审核中 2: 未通过 3: 已通过',
  `award` DECIMAL(9,2) NULL DEFAULT 0 COMMENT '每个任务的奖励',
  `final_award` DECIMAL(9,2) NULL DEFAULT 0 COMMENT '单个任务计算费率后的最终价格',
  `contact_name` VARCHAR(10) NULL COMMENT '联系人',
  `contact_phone` VARCHAR(20) NULL COMMENT '联系人手机号',
  `description` VARCHAR(100) NULL COMMENT '任务简单描述',
  `quest_detail` VARCHAR(1000) NULL COMMENT '详细描述',
  `url` VARCHAR(255) NULL COMMENT '任务链接URL',
  `memo` VARCHAR(100) NULL COMMENT '其它说明',
  `offline` TINYINT(1) NULL DEFAULT 0 COMMENT '是否已经下线',
  `province_id` INT NULL COMMENT '任务对象：省',
  `city_id` INT NULL COMMENT '任务对象：市',
  `region_id` INT NULL COMMENT '任务对象:区',
  `college_id` INT NULL COMMENT '任务对象：大学',
  `school_id` INT NULL COMMENT '任务对象: 学院',
  `question_amt` INT NULL DEFAULT 0 COMMENT '题目数量, 仅当分类为答题问卷时可用',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_created_time` (`created_time` ASC)  COMMENT '',
  INDEX `idx_quest_cate_id` (`quest_cate_id` ASC)  COMMENT '',
  INDEX `idx_award` (`award` ASC)  COMMENT '',
  INDEX `idx_offline` (`offline` ASC)  COMMENT '',
  INDEX `idx_start_time` (`start_time` ASC)  COMMENT '',
  INDEX `idx_end_time` (`end_time` ASC)  COMMENT '',
  INDEX `idx_left_amt` (`left_amt` ASC)  COMMENT '',
  INDEX `idx_emp_status` (`emp_status` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '轻兼职表';


-- -----------------------------------------------------
-- Table `taolijie`.`quest_assign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`quest_assign` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`quest_assign` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `member_id` INT NOT NULL COMMENT '领取者用户id',
  `username` VARCHAR(45) NULL COMMENT '领取者用户名',
  `quest_id` INT NOT NULL COMMENT '任务id',
  `quest_title` VARCHAR(45) NULL COMMENT '任取的任务的标题',
  `assign_time` DATETIME NULL COMMENT '领取时间',
  `status` VARCHAR(3) NULL DEFAULT '00' COMMENT '00: 已领取. 01: 已完成 02: 已超时 03: 已提交',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_assign_time` (`assign_time` ASC)  COMMENT '',
  INDEX `idx_member_id` (`member_id` ASC)  COMMENT '',
  INDEX `idx_member_id_and_assign_time` (`member_id` ASC, `assign_time` ASC)  COMMENT '',
  INDEX `idx_member_id_and_status` (`member_id` ASC, `status` ASC)  COMMENT '',
  INDEX `idx_quest_id` (`quest_id` ASC)  COMMENT '',
  INDEX `idx_member_id_and_quest_id` (`member_id` ASC, `quest_id` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '任务领取表';


-- -----------------------------------------------------
-- Table `taolijie`.`withdraw_apply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`withdraw_apply` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`withdraw_apply` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `member_id` INT NOT NULL COMMENT '申请者id',
  `acc_id` INT NOT NULL COMMENT '现金账户id\n',
  `username` VARCHAR(45) NULL COMMENT '申请者用户名',
  `apply_time` DATETIME NULL COMMENT '申请时间',
  `amount` DECIMAL(5,2) NULL COMMENT '提现金额',
  `status` VARCHAR(3) NULL DEFAULT '00' COMMENT '00: 等待审核 01: 等待派现 02: 已完成 03: 审核不通过',
  `update_time` DATETIME NULL COMMENT '状态更新时间',
  `alipay_acc` VARCHAR(45) NULL COMMENT '支付宝账号',
  `bank_acc` VARCHAR(45) NULL COMMENT '银行卡号',
  `memo` VARCHAR(200) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_member_id` (`member_id` ASC)  COMMENT '',
  INDEX `idx_username` (`username` ASC)  COMMENT '',
  INDEX `idx_member_id_and_status` (`member_id` ASC, `status` ASC)  COMMENT '',
  INDEX `idx_status` (`status` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '提现申请';


-- -----------------------------------------------------
-- Table `taolijie`.`cash_acc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`cash_acc` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`cash_acc` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `available_balance` DECIMAL(9,2) NULL DEFAULT 0 COMMENT '可用余额',
  `frozen_balance` DECIMAL(9,2) NULL DEFAULT 0 COMMENT '被冻结的金额',
  `total_balance` DECIMAL(9,2) NULL DEFAULT 0 COMMENT '总余额',
  `status` VARCHAR(3) NULL DEFAULT '00' COMMENT '00: 正常 01: 冻结',
  `update_time` DATETIME NULL COMMENT '最后更新时间',
  `created_time` DATETIME NULL COMMENT '',
  `member_id` INT NOT NULL COMMENT '',
  `username` VARCHAR(45) NULL COMMENT '冗余字段，用户名',
  `member_role` VARCHAR(20) NULL COMMENT '冗余字段，用户的角色名',
  `deal_password` VARCHAR(90) NULL COMMENT '交易密码',
  `phone_number` VARCHAR(20) NULL COMMENT '手机号',
  `bank_acc` VARCHAR(45) NULL COMMENT '',
  `alipay_acc` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `name` VARCHAR(10) NULL COMMENT '用户真实姓名',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_member_id` (`member_id` ASC)  COMMENT '',
  INDEX `idx_status` (`status` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '现金账户表';


-- -----------------------------------------------------
-- Table `taolijie`.`acc_flow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`acc_flow` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`acc_flow` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `created_time` DATETIME NULL COMMENT '',
  `acc_id` INT NOT NULL COMMENT '',
  `action_type` VARCHAR(3) NULL COMMENT '00: 提现 01:充值 02:冻结 03:退款 04: 赏金',
  `ava_balance_ch` DECIMAL(9,2) NULL DEFAULT 0 COMMENT '可用余额变化值 ',
  `fro_balance_ch` DECIMAL(9,2) NULL DEFAULT 0 COMMENT '冻结余额变化值 ',
  `tot_balance_ch` DECIMAL(9,2) NULL DEFAULT 0 COMMENT '总余额变化值',
  `ava_balance_new` DECIMAL(9,2) NULL DEFAULT 0 COMMENT '最新可用余额',
  `fro_balance_new` DECIMAL(9,2) NULL DEFAULT 0 COMMENT '最新冻结余额',
  `tot_balance_new` DECIMAL(9,2) NULL DEFAULT 0 COMMENT '最新总余额',
  `memo` VARCHAR(200) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_acc_id` (`acc_id` ASC)  COMMENT '',
  INDEX `idx_acc_id_and_created_time` (`acc_id` ASC, `created_time` ASC)  COMMENT '',
  INDEX `idx_acc_id_and_action_type` (`acc_id` ASC, `action_type` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '现金账户流水';


-- -----------------------------------------------------
-- Table `taolijie`.`finish_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`finish_request` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`finish_request` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `quest_id` INT NOT NULL COMMENT '任务id',
  `member_id` INT NOT NULL COMMENT '申请者用户id',
  `username` VARCHAR(45) NULL COMMENT '冗余字段,申请者的用户名',
  `reg_name` VARCHAR(45) NULL COMMENT '如果是app推广，则这里是注册用户名',
  `created_time` DATETIME NULL COMMENT '申请时间',
  `audit_time` DATETIME NULL COMMENT '审核完成时间',
  `description` VARCHAR(500) NULL COMMENT '任务完成情况文字描述',
  `image_ids` VARCHAR(500) NULL COMMENT '上传图片id',
  `status` VARCHAR(3) NULL DEFAULT '01' COMMENT '01: 等待审核 \n02: 商家审核未通过 03: tlj审核未通过 \n04:自动通过 \n05:商家审核通过 06: tlj审核通过',
  `memo` VARCHAR(500) NULL COMMENT '审核说明',
  `name` VARCHAR(10) NULL COMMENT '用户姓名',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_member_id` (`member_id` ASC)  COMMENT '',
  INDEX `idx_quest_id` (`quest_id` ASC)  COMMENT '',
  INDEX `idx_created_time` (`created_time` ASC)  COMMENT '',
  INDEX `idx_audit_time` (`audit_time` ASC)  COMMENT '',
  INDEX `idx_status` (`status` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '任务完成审核表';


-- -----------------------------------------------------
-- Table `taolijie`.`sys_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`sys_config` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`sys_config` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `quest_fee_rate` INT NULL COMMENT '整数表示百分比, 5表示5%, 200表示200%',
  `audit_fee` DECIMAL(5,2) NULL COMMENT '任务审核费(单条)',
  `top_fee` DECIMAL(5,2) NULL COMMENT '帖子置顶费(条/小时)',
  `tag_fee` DECIMAL(5,2) NULL COMMENT '打推荐标签费(小时)',
  `question_fee` DECIMAL(5,2) NULL COMMENT '答题任务一道题的费用',
  `survey_fee` DECIMAL(5,2) NULL COMMENT '问卷调查一个问题的费用',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '系统配置表';


-- -----------------------------------------------------
-- Table `taolijie`.`pay_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`pay_order` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`pay_order` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cash_acc_id` INT NOT NULL COMMENT '订单对应的现金账户',
  `member_id` INT NOT NULL COMMENT '订单生成者id',
  `title` VARCHAR(45) NOT NULL COMMENT '订单标题',
  `created_time` DATETIME NOT NULL COMMENT '订单创建时间',
  `update_time` DATETIME NULL COMMENT '状态更新时间 ',
  `amount` DECIMAL(9,2) NOT NULL COMMENT '订单金额',
  `type` VARCHAR(3) NOT NULL COMMENT '订单类型. 00: 充值订单 01: 任务置顶 02: 加tag 03: 发布任务',
  `status` VARCHAR(3) NOT NULL COMMENT '订单状态. 00:等待支付 01: 交易成功 02: 支付失败 03: 支付成功',
  `pay_chan` INT NOT NULL COMMENT '支付渠道. 0: alipay, 1: wechat',
  `alipay_trade_num` VARCHAR(70) NULL COMMENT '支付宝交易号',
  `memo` VARCHAR(200) NULL COMMENT '审核备注',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_cash_acc_id` (`cash_acc_id` ASC)  COMMENT '',
  INDEX `idx_created_time` (`created_time` ASC)  COMMENT '',
  INDEX `idx_amount` (`amount` ASC)  COMMENT '',
  INDEX `idx_acc_id_and_type` (`cash_acc_id` ASC, `type` ASC)  COMMENT '',
  INDEX `idx_acc_id_and_type_and_status` (`cash_acc_id` ASC, `type` ASC, `status` ASC)  COMMENT '',
  INDEX `idx_acc_id_status` (`status` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '支付订单表';


-- -----------------------------------------------------
-- Table `taolijie`.`dict_province`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`dict_province` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`dict_province` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(30) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '省表';


-- -----------------------------------------------------
-- Table `taolijie`.`dict_city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`dict_city` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`dict_city` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(20) NULL COMMENT '',
  `province_id` INT NULL COMMENT '所属于的省，没有则是直辖市',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`dict_region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`dict_region` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`dict_region` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(30) NULL COMMENT '',
  `province_id` INT NULL COMMENT '所属的省',
  `city_id` INT NULL COMMENT '所属的市',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`dict_college`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`dict_college` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`dict_college` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `full_name` VARCHAR(45) NULL COMMENT '',
  `short_name` VARCHAR(10) NULL COMMENT '',
  `province_id` INT NULL COMMENT '',
  `city_id` INT NULL COMMENT '',
  `region_id` INT NULL COMMENT '',
  `address` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`dict_school`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`dict_school` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`dict_school` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `full_name` VARCHAR(45) NULL COMMENT '',
  `short_name` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`stu_certi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`stu_certi` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`stu_certi` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `created_time` DATETIME NULL COMMENT '',
  `update_time` DATETIME NULL COMMENT '',
  `member_id` INT NOT NULL COMMENT '',
  `username` VARCHAR(45) NULL COMMENT '冗余字段username',
  `name` VARCHAR(10) NULL COMMENT '认证姓名',
  `college_id` INT NULL COMMENT '认证大学',
  `school_id` INT NULL COMMENT '认证学院',
  `clazz` VARCHAR(20) NULL COMMENT '班级',
  `pic_ids` VARCHAR(100) NULL COMMENT '图片id',
  `status` VARCHAR(3) NULL COMMENT '00: 等待审核 01: 审核通过 02; 审核失败',
  `memo` VARCHAR(200) NULL COMMENT '审核原因说明',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '学生认证信息表';


-- -----------------------------------------------------
-- Table `taolijie`.`emp_certi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`emp_certi` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`emp_certi` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `member_id` INT NOT NULL COMMENT '',
  `username` VARCHAR(45) NULL COMMENT '冗余字段username',
  `company_name` VARCHAR(45) NULL COMMENT '',
  `address` VARCHAR(45) NULL COMMENT '',
  `pic_ids` VARCHAR(100) NULL COMMENT '',
  `status` VARCHAR(3) NULL COMMENT '00: 等待审核 01: 审核通过 02; 审核失败',
  `created_time` DATETIME NULL COMMENT '',
  `update_time` DATETIME NULL COMMENT '',
  `memo` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`seq_avatar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`seq_avatar` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`seq_avatar` (
  `int` INT NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`int`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`seq_sh`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`seq_sh` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`seq_sh` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`seq_job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`seq_job` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`seq_job` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`quest_college_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`quest_college_rel` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`quest_college_rel` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `quest_id` INT NOT NULL COMMENT '',
  `college_id` INT NOT NULL COMMENT '',
  `college_name` VARCHAR(45) NULL COMMENT '冗余字段',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_quest_id` (`quest_id` ASC)  COMMENT '',
  INDEX `idx_college_id` (`college_id` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '任务对象, 任务学校关联表';


-- -----------------------------------------------------
-- Table `taolijie`.`quest_school_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`quest_school_rel` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`quest_school_rel` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `quest_id` INT NOT NULL COMMENT '',
  `school_id` INT NOT NULL COMMENT '',
  `school_name` VARCHAR(45) NULL COMMENT '冗余字段',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_quest_id` (`quest_id` ASC)  COMMENT '',
  INDEX `idx_school_id` (`school_id` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '任务对象: 任务学院关联表';


-- -----------------------------------------------------
-- Table `taolijie`.`tlj_audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`tlj_audit` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`tlj_audit` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `quest_id` INT NOT NULL COMMENT '',
  `quest_title` VARCHAR(45) NULL COMMENT '任务标题',
  `tot_amt` INT NOT NULL COMMENT '家商申请的总数量',
  `left_amt` INT NOT NULL COMMENT '该次审核的剩余数量',
  `emp_id` INT NOT NULL COMMENT '商家用户id',
  `emp_username` VARCHAR(45) NULL COMMENT '商家用户名',
  `created_time` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_quest_id` (`quest_id` ASC)  COMMENT '',
  INDEX `idx_left_amt` (`left_amt` ASC)  COMMENT '',
  INDEX `idx_emp_id` (`emp_id` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '桃李街审核记录表';


-- -----------------------------------------------------
-- Table `taolijie`.`collection_quest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`collection_quest` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`collection_quest` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `created_time` DATETIME NOT NULL COMMENT '',
  `member_id` INT NOT NULL COMMENT '收藏者id',
  `quest_id` INT NOT NULL COMMENT '任务id',
  `quest_title` VARCHAR(45) NULL COMMENT '冗余字段,任务标题',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_mem_id` (`member_id` ASC)  COMMENT '',
  INDEX `idx_created_time` (`created_time` ASC)  COMMENT '',
  INDEX `idx_mem_and_time` (`member_id` ASC, `created_time` ASC)  COMMENT '',
  INDEX `idx_quest_id` (`quest_id` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '轻兼职收藏表';


-- -----------------------------------------------------
-- Table `taolijie`.`reco_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`reco_post` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`reco_post` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `post_id` INT NOT NULL COMMENT '',
  `title` VARCHAR(45) NULL COMMENT '冗余字段',
  `type` INT NOT NULL COMMENT '0: 兼职 1:二手 2:简历 3:任务',
  `member_id` INT NULL COMMENT '申请者id',
  `created_time` DATETIME NULL COMMENT '',
  `audit_time` DATETIME NULL COMMENT '',
  `expired_time` DATETIME NULL COMMENT '过期时间',
  `order_index` INT NULL DEFAULT 100 COMMENT '排序使用，从0开始，越小越靠前',
  `valid` TINYINT(1) NULL DEFAULT 0 COMMENT '是否生效',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_mem_id` (`member_id` ASC)  COMMENT '',
  INDEX `idx_post_id` (`post_id` ASC)  COMMENT '',
  INDEX `idx_type` (`type` ASC)  COMMENT '',
  INDEX `idx_valid` (`valid` ASC)  COMMENT '',
  INDEX `idx_order_index` (`order_index` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '信息推荐表';


-- -----------------------------------------------------
-- Table `taolijie`.`quest_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`quest_question` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`quest_question` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `created_time` DATETIME NOT NULL COMMENT '',
  `content` VARCHAR(100) NULL COMMENT '问题内容',
  `quest_id` INT NOT NULL COMMENT '',
  `order_index` INT NULL DEFAULT 0 COMMENT '',
  `type` INT NULL COMMENT '0: 答题 1:问卷',
  `user_amt` INT NULL DEFAULT 0 COMMENT '参与答题的人数',
  `correct_amt` INT NULL DEFAULT 0 COMMENT '答对题目的人数',
  `answer_amt` INT NULL DEFAULT 1 COMMENT '选对几个才算答对',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_order_index` (`order_index` ASC)  COMMENT '',
  INDEX `idx_type` (`type` ASC)  COMMENT '',
  INDEX `idx_quest_id` (`quest_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`question_opt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`question_opt` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`question_opt` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `opt_name` VARCHAR(5) NOT NULL COMMENT '选项名',
  `opt_content` VARCHAR(45) NOT NULL COMMENT '选项内容',
  `question_id` INT NULL COMMENT '选择属于的问题',
  `answer_amt` INT NULL DEFAULT 0 COMMENT '选择该选项的人数',
  `correct` TINYINT(1) NULL DEFAULT 0 COMMENT '该选项是否正确',
  `order_index` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_question_id` (`question_id` ASC)  COMMENT '',
  INDEX `idx_index` (`order_index` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`answer_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`answer_record` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`answer_record` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `created_time` DATETIME NOT NULL COMMENT '',
  `question_id` INT NOT NULL COMMENT '问题d',
  `member_id` INT NOT NULL COMMENT '答题者id',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_opt_mem_id` (`question_id` ASC, `member_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`secret_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`secret_question` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`secret_question` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `created_time` DATETIME NOT NULL COMMENT '',
  `member_id` INT NOT NULL COMMENT '密保用户id',
  `acc_id` INT NOT NULL COMMENT '对应的钱包id',
  `content` VARCHAR(45) NOT NULL COMMENT '',
  `answer` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_acc_id` (`acc_id` ASC)  COMMENT '',
  INDEX `idx_mem_id` (`member_id` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = '密保问题';


-- -----------------------------------------------------
-- Table `taolijie`.`coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`coupon` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`coupon` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `code` VARCHAR(40) NOT NULL COMMENT '优惠券编码',
  `created_time` DATETIME NOT NULL COMMENT '',
  `acquire_time` DATETIME NULL COMMENT '学生领取时间',
  `emp_id` INT NOT NULL COMMENT '发券的商家id',
  `mem_id` INT NULL COMMENT '领取者用户id',
  `quest_title` VARCHAR(45) NULL COMMENT '冗余字段, 任务的标题',
  `quest_id` INT NOT NULL COMMENT '对应的任务id',
  `comp_name` VARCHAR(45) NULL COMMENT '店名',
  `title` VARCHAR(45) NOT NULL COMMENT '',
  `description` VARCHAR(80) NULL COMMENT '优惠券描述',
  `expired_time` DATETIME NOT NULL COMMENT '',
  `logo_path` VARCHAR(150) NULL COMMENT '',
  `status` INT NOT NULL COMMENT '0: 未被领取 1:已领取 2:已使用',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_emp_id` (`emp_id` ASC)  COMMENT '',
  INDEX `idx_code` (`code` ASC)  COMMENT '',
  INDEX `idx_status` (`status` ASC)  COMMENT '',
  INDEX `idx_quest_id` (`quest_id` ASC)  COMMENT '',
  INDEX `idx_mem_id` (`mem_id` ASC)  COMMENT '',
  INDEX `idx_acquire_time` (`acquire_time` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`quest_city_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`quest_city_rel` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`quest_city_rel` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `quest_id` INT NOT NULL COMMENT '',
  `city_id` INT NOT NULL COMMENT '',
  `city_name` VARCHAR(25) NULL COMMENT '冗余字段',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_quest_id` (`quest_id` ASC)  COMMENT '',
  INDEX `idx_city_id` (`city_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taolijie`.`quest_province_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taolijie`.`quest_province_rel` ;

CREATE TABLE IF NOT EXISTS `taolijie`.`quest_province_rel` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `province_id` INT NOT NULL COMMENT '',
  `quest_id` INT NOT NULL COMMENT '',
  `province_name` VARCHAR(25) NULL COMMENT '冗余字段',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_pro_id` (`province_id` ASC)  COMMENT '',
  INDEX `idx_quest_id` (`quest_id` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
