package com.fh.taolijie.dao.mapper.v2;

import com.fh.taolijie.domain.ParticipantModel;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ParticipantModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participant
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participant
     *
     * @mbggenerated
     */
    int insert(ParticipantModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participant
     *
     * @mbggenerated
     */
    int insertSelective(ParticipantModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participant
     *
     * @mbggenerated
     */
    ParticipantModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participant
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ParticipantModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participant
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ParticipantModel record);

    List<ParticipantModel> findBy(ParticipantModel model);
}