package com.fh.taolijie.dao.mapper.v2;

import com.fh.taolijie.domain.v2.SchoolOrgModel;
import com.fh.taolijie.domain.v2.SchoolOrgModelWithBLOBs;

public interface SchoolOrgModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_organization
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_organization
     *
     * @mbggenerated
     */
    int insert(SchoolOrgModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_organization
     *
     * @mbggenerated
     */
    int insertSelective(SchoolOrgModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_organization
     *
     * @mbggenerated
     */
    SchoolOrgModelWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SchoolOrgModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SchoolOrgModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SchoolOrgModel record);
}