package com.fh.taolijie.dao.mapper.v2;

import com.fh.taolijie.domain.v2.SchoolOrgModel;

public interface SchoolOrgModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_organization
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_organization
     *
     * @mbggenerated
     */
    int insert(SchoolOrgModel model);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_organization
     *
     * @mbggenerated
     */
    int insertSelective(SchoolOrgModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_organization
     *
     * @mbggenerated
     */
    SchoolOrgModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SchoolOrgModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SchoolOrgModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SchoolOrgModel record);
}