package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.AccFlowModel;
import com.fh.taolijie.domain.AccFlowModelExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AccFlowModelMapper {
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    int insert(AccFlowModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    int insertSelective(AccFlowModel record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    AccFlowModel selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccFlowModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccFlowModel record);


    List<AccFlowModel> selectByAccId(@Param("accId") Integer accId, @Param("start") Date start, @Param("end") Date end, @Param("pn") int pn, @Param("ps") int ps);
    long countSelectByAccId(@Param("accId") Integer accId, @Param("start") Date start, @Param("end") Date end);



    List<AccFlowModel> selectByAccIdAndInterval(@Param("accId") Integer accId,
                                                @Param("start") Date start,
                                                @Param("end") Date end,
                                                @Param("pn") int pn,
                                                @Param("ps") int ps);
    long countSelectByAccIdAndInterval(@Param("accId") Integer accId,
                                       @Param("start") Date start,
                                       @Param("end") Date end);

}