package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.AccFlowModel;
import com.fh.taolijie.domain.AccFlowModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AccFlowModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    int countByExample(AccFlowModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    int deleteByExample(AccFlowModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    int insert(AccFlowModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    int insertSelective(AccFlowModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    List<AccFlowModel> selectByExample(AccFlowModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    AccFlowModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AccFlowModel record, @Param("example") AccFlowModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AccFlowModel record, @Param("example") AccFlowModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccFlowModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccFlowModel record);
}