package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.acc.CollectionModel;
import com.fh.taolijie.domain.acc.CollectionModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CollectionModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int countByExample(CollectionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int insert(CollectionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int insertSelective(CollectionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    List<CollectionModel> selectByExample(CollectionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    CollectionModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CollectionModel record, @Param("example") CollectionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CollectionModel record, @Param("example") CollectionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CollectionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CollectionModel record);

    boolean isMemberAndJobExists(@Param("memberId") Integer memberId, @Param("jobId") Integer jobId);

    boolean isMemberAndShExists(@Param("memberId") Integer memberId, @Param("shId") Integer shId);

    boolean isMemberAndResumeExists(@Param("memberId") Integer memberId, @Param("resumeId") Integer resumeId);

    int deleteByMemberAndJob(@Param("memberId") Integer memberId, @Param("jobId") Integer jobId);
    int deleteByMemberAndSh(@Param("memberId") Integer memberId, @Param("shId") Integer shId);
    int deleteByMemberAndResume(@Param("memberId") Integer memberId, @Param("resumeId") Integer resumeId);
}