package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.CollectionModel;
import com.fh.taolijie.domain.CollectionModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CollectionModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int countByExample(CollectionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int insert(CollectionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int insertSelective(CollectionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    List<CollectionModel> selectByExample(CollectionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    CollectionModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CollectionModel record, @Param("example") CollectionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CollectionModel record, @Param("example") CollectionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CollectionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CollectionModel record);
}