package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.CouponModel;
import org.springframework.stereotype.Repository;

@Repository
public interface CouponModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated
     */
    int insert(CouponModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated
     */
    int insertSelective(CouponModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated
     */
    CouponModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CouponModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CouponModel record);
}