package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.dict.DictCityModel;
import com.fh.taolijie.domain.dict.DictCityModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface DictCityModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbggenerated
     */
    int countByExample(DictCityModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbggenerated
     */
    int deleteByExample(DictCityModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbggenerated
     */
    int insert(DictCityModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbggenerated
     */
    int insertSelective(DictCityModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbggenerated
     */
    List<DictCityModel> selectByExample(DictCityModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbggenerated
     */
    DictCityModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DictCityModel record, @Param("example") DictCityModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DictCityModel record, @Param("example") DictCityModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DictCityModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DictCityModel record);

    List<DictCityModel> selectAll();
}