package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.dict.DictProvinceModel;
import com.fh.taolijie.domain.dict.DictProvinceModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface DictProvinceModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbggenerated
     */
    int countByExample(DictProvinceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbggenerated
     */
    int deleteByExample(DictProvinceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbggenerated
     */
    int insert(DictProvinceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbggenerated
     */
    int insertSelective(DictProvinceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbggenerated
     */
    List<DictProvinceModel> selectByExample(DictProvinceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbggenerated
     */
    DictProvinceModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DictProvinceModel record, @Param("example") DictProvinceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DictProvinceModel record, @Param("example") DictProvinceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DictProvinceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DictProvinceModel record);
}