package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.DictSchoolModel;
import com.fh.taolijie.domain.DictSchoolModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface DictSchoolModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_school
     *
     * @mbggenerated
     */
    int countByExample(DictSchoolModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_school
     *
     * @mbggenerated
     */
    int deleteByExample(DictSchoolModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_school
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_school
     *
     * @mbggenerated
     */
    int insert(DictSchoolModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_school
     *
     * @mbggenerated
     */
    int insertSelective(DictSchoolModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_school
     *
     * @mbggenerated
     */
    List<DictSchoolModel> selectByExample(DictSchoolModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_school
     *
     * @mbggenerated
     */
    DictSchoolModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_school
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DictSchoolModel record, @Param("example") DictSchoolModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_school
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DictSchoolModel record, @Param("example") DictSchoolModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_school
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DictSchoolModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_school
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DictSchoolModel record);
}