package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.EmpCertiModel;
import com.fh.taolijie.domain.EmpCertiModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface EmpCertiModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_certi
     *
     * @mbggenerated
     */
    int countByExample(EmpCertiModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_certi
     *
     * @mbggenerated
     */
    int deleteByExample(EmpCertiModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_certi
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_certi
     *
     * @mbggenerated
     */
    int insert(EmpCertiModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_certi
     *
     * @mbggenerated
     */
    int insertSelective(EmpCertiModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_certi
     *
     * @mbggenerated
     */
    List<EmpCertiModel> selectByExample(EmpCertiModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_certi
     *
     * @mbggenerated
     */
    EmpCertiModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_certi
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EmpCertiModel record, @Param("example") EmpCertiModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_certi
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EmpCertiModel record, @Param("example") EmpCertiModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_certi
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmpCertiModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_certi
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmpCertiModel record);
}