package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.FeedbackModel;
import com.fh.taolijie.domain.FeedbackModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface FeedbackModelMapper {
    long countByExample(FeedbackModelExample example);

    int deleteByPrimaryKey(Integer id);

    void deleteByPkInBatch(List<Integer> idList);

    int insert(FeedbackModel record);

    int insertSelective(FeedbackModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated
     */
    List<FeedbackModel> selectByExample(FeedbackModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated
     */
    FeedbackModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FeedbackModel record, @Param("example") FeedbackModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FeedbackModel record, @Param("example") FeedbackModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FeedbackModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FeedbackModel record);
}