package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.JobPostCategoryModel;
import org.apache.ibatis.annotations.Param;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.cache.annotation.Caching;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface JobPostCategoryModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post_category
     *
     * @mbggenerated
     */
    @Caching(
            evict = {
                    @CacheEvict(value = "jobCategoryCache", key = "'JobPostCategory:id:'.concat(#p0)", beforeInvocation = true ),
                    @CacheEvict(value = "jobCategoryListCache", allEntries = true, beforeInvocation = true )
            }
    )
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post_category
     *
     * @mbggenerated
     */
    @CacheEvict(value = "jobCategoryListCache", allEntries = true, beforeInvocation = true)
    int insert(JobPostCategoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post_category
     *
     * @mbggenerated
     */
    @CacheEvict(value = "jobCategoryListCache", allEntries = true, beforeInvocation = true )
    int insertSelective(JobPostCategoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post_category
     *
     * @mbggenerated
     */
    @Cacheable(value = "jobCategoryCache", key = "'JobPostCategory:id:'.concat(#p0)")
    JobPostCategoryModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post_category
     *
     * @mbggenerated
     */
    @Caching(
            evict = {
                    @CacheEvict(value = "jobCategoryCache", key = "'JobPostCategory:id:'.concat(#p0.id)", beforeInvocation = true ),
                    @CacheEvict(value = "jobCategoryListCache", allEntries = true, beforeInvocation = true )
            }
    )
    int updateByPrimaryKeySelective(JobPostCategoryModel record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post_category
     *
     * @mbggenerated
     */
    @Caching(
            evict = {
                    @CacheEvict(value = "jobCategoryCache", key = "'JobPostCategory:id:'.concat(#p0.id)", beforeInvocation = true ),
                    @CacheEvict(value = "jobCategoryListCache", allEntries = true, beforeInvocation = true )
            }
    )
    int updateByPrimaryKey(JobPostCategoryModel record);

    @Cacheable(value = "jobCategoryListCache", key = "'JobPostCategory:query:all:'.concat(#p0).concat(':').concat(#p1)")
    List<JobPostCategoryModel> getAll(@Param("pageNumber") int pageNumber, @Param("pageSize") int pageSize);

    boolean isCategoryEmpty(Integer categoryId);
}