package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.JobPostModel;
import com.fh.taolijie.domain.JobPostModelWithBLOBs;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface JobPostModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post
     *
     * @mbggenerated
     */
    int insert(JobPostModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post
     *
     * @mbggenerated
     */
    int insertSelective(JobPostModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post
     *
     * @mbggenerated
     */
    JobPostModelWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JobPostModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(JobPostModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JobPostModel record);

    List<JobPostModel> getAll(@Param("pageNumber") int pageNumber, @Param("pageSize") int pageSize);

    List<JobPostModel> getInBatch(List<Integer> idList);

    List<JobPostModel> getByComplaint(@Param("pageNumber") int pageNumber, @Param("pageSize") int pageSize);


    /*List<JobPostModel> getByMember(@Param("memberId") Integer memberId, @Param("pageNumber") int pageNumber, @Param("pageSize") int pageSize);

    List<JobPostModel> getByCategory(@Param("categoryId") Integer categoryId, @Param("pageNumber") int pageNumber, @Param("pageSize") int pageSize);*/

    List<JobPostModel> findBy(JobPostModel model);

    void complaint(Integer postId);

    void increasePageView(Integer postId);
}