package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.JobPostModel;
import com.fh.taolijie.domain.JobPostModelWithBLOBs;
import org.springframework.stereotype.Repository;

@Repository
public interface JobPostModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post
     *
     * @mbggenerated
     */
    int insert(JobPostModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post
     *
     * @mbggenerated
     */
    int insertSelective(JobPostModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post
     *
     * @mbggenerated
     */
    JobPostModelWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JobPostModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(JobPostModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JobPostModel record);
}