package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.PrivateNotificationModel;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;

@Repository
public interface NotificationModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated
     */
    int insert(PrivateNotificationModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated
     */
    int insertSelective(PrivateNotificationModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated
     */
    PrivateNotificationModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PrivateNotificationModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PrivateNotificationModel record);

    List<PrivateNotificationModel> findBy(PrivateNotificationModel model);

    List<PrivateNotificationModel> findByTimeRange(@Param("memberId")Integer memberId, @Param("roleName") String roleName, @Param("startTime") Date startTime, @Param("endTime") Date endTime, @Param("pageNumber") int pageNumber, @Param("pageSize") int pageSize);

    Long getNotificationAmount(@Param("memberId") Integer memberId, @Param("isRead") boolean isRead)
            ;
}