package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.order.PayOrderModel;

import java.util.List;

import org.springframework.stereotype.Repository;

@Repository
public interface PayOrderModelMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbggenerated
     */
    int insert(PayOrderModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbggenerated
     */
    int insertSelective(PayOrderModel record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbggenerated
     */
    PayOrderModel selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayOrderModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayOrderModel record);

    List<PayOrderModel> findBy(PayOrderModel example);
    long countFindBy(PayOrderModel example);
}