package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.PrivateNotificationModel;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Created by wanghongfei on 15-6-13.
 */
@Repository
public interface PrivateNotificationModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notification
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notification
     *
     * @mbggenerated
     */
    int insert(PrivateNotificationModel model);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notification
     *
     * @mbggenerated
     */
    int insertSelective(PrivateNotificationModel model);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notification
     *
     * @mbggenerated
     */
    PrivateNotificationModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notification
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PrivateNotificationModel model);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_notification
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PrivateNotificationModel model);


    List<PrivateNotificationModel> findBy(PrivateNotificationModel model);
    long countFindBy(PrivateNotificationModel model);

    int markAsReadInBatch(List<Integer> idList);

    List<PrivateNotificationModel> findInBatch(List<Integer> idList);
}
