package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.quest.QuestCategoryModel;
import com.fh.taolijie.domain.quest.QuestCategoryModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface QuestCategoryModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_cate
     *
     * @mbggenerated
     */
    int countByExample(QuestCategoryModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_cate
     *
     * @mbggenerated
     */
    int deleteByExample(QuestCategoryModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_cate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_cate
     *
     * @mbggenerated
     */
    int insert(QuestCategoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_cate
     *
     * @mbggenerated
     */
    int insertSelective(QuestCategoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_cate
     *
     * @mbggenerated
     */
    List<QuestCategoryModel> selectByExample(QuestCategoryModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_cate
     *
     * @mbggenerated
     */
    QuestCategoryModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_cate
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QuestCategoryModel record, @Param("example") QuestCategoryModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_cate
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QuestCategoryModel record, @Param("example") QuestCategoryModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_cate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuestCategoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_cate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuestCategoryModel record);

    List<QuestCategoryModel> findBy(QuestCategoryModel model);
    long countFindBy(QuestCategoryModel model);


    boolean checkCateEmpty(Integer cateId);
}