package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.QuestSchRelModel;
import org.springframework.stereotype.Repository;

@Repository
public interface QuestSchRelModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_school_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_school_rel
     *
     * @mbggenerated
     */
    int insert(QuestSchRelModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_school_rel
     *
     * @mbggenerated
     */
    int insertSelective(QuestSchRelModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_school_rel
     *
     * @mbggenerated
     */
    QuestSchRelModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_school_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuestSchRelModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_school_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuestSchRelModel record);
}