package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.quest.QuestModel;

import java.util.List;

import org.springframework.stereotype.Repository;

@Repository
public interface QuestModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated
     */
    int insert(QuestModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated
     */
    int insertSelective(QuestModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated
     */
    QuestModel selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuestModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuestModel record);


    /**
     * 查询剩余任务数量，加行锁
     * @param questId
     * @return
     */
    int selectQuestLeftAmountWithLock(Integer questId);

    boolean checkQuestIdExists(Integer questId);

    void decreaseLeftAmount(Integer questId);
    void increaseLeftAmount(Integer questId);

    List<QuestModel> findBy(QuestModel model);
    long countFindBy(QuestModel model);
}