package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.QuestCiRel;
import org.springframework.stereotype.Repository;

@Repository
public interface QuestCiRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_city_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_city_rel
     *
     * @mbggenerated
     */
    int insert(QuestCiRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_city_rel
     *
     * @mbggenerated
     */
    int insertSelective(QuestCiRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_city_rel
     *
     * @mbggenerated
     */
    QuestCiRel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_city_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuestCiRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_city_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuestCiRel record);
}