package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.QuestionModel;
import org.springframework.stereotype.Repository;

@Repository
public interface QuestionModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_question
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_question
     *
     * @mbggenerated
     */
    int insert(QuestionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_question
     *
     * @mbggenerated
     */
    int insertSelective(QuestionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_question
     *
     * @mbggenerated
     */
    QuestionModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_question
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuestionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_question
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuestionModel record);
}