package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.cache.annotation.NoCache;
import com.fh.taolijie.domain.RecommendedPostModel;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RecommendedPostModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommended_post
     *
     * @mbggenerated
     */
    @NoCache
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommended_post
     *
     * @mbggenerated
     */
    @NoCache
    int insert(RecommendedPostModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommended_post
     *
     * @mbggenerated
     */
    @NoCache
    int insertSelective(RecommendedPostModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommended_post
     *
     * @mbggenerated
     */
    @NoCache
    RecommendedPostModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommended_post
     *
     * @mbggenerated
     */
    @NoCache
    int updateByPrimaryKeySelective(RecommendedPostModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommended_post
     *
     * @mbggenerated
     */
    @NoCache
    int updateByPrimaryKey(RecommendedPostModel record);

    /**
     * shId, jobId, resumeId三者只能一个有值，否则会报错!
     * @param model
     * @return
     */
    @NoCache
    List<RecommendedPostModel> findBy(RecommendedPostModel model);
    @NoCache
    int countFindBy(RecommendedPostModel model);

    @NoCache
    List<RecommendedPostModel> findRecommendList(RecommendedPostModel model);
    @NoCache
    int countFindRecommendList(RecommendedPostModel model);

    boolean checkRecommendExist(RecommendedPostModel model);
}