package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.ResumeModel;
import com.fh.taolijie.domain.ResumeModelWithBLOBs;
import org.springframework.stereotype.Repository;

@Repository
public interface ResumeModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated
     */
    int insert(ResumeModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated
     */
    int insertSelective(ResumeModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated
     */
    ResumeModelWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ResumeModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ResumeModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ResumeModel record);
}