package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.ResumeModel;
import com.fh.taolijie.domain.middle.ResumePostRecord;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ResumeModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated
     */
    int insert(ResumeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated
     */
    int insertSelective(ResumeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated
     */
    ResumeModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ResumeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ResumeModel record);

    List<ResumeModel> getAll(@Param("pageNumber") int pageNumber, @Param("pageSize") int pageSize);
    long countGetAll();

    List<ResumeModel> findBy(ResumeModel model);
    long countFindBy(ResumeModel model);

    List<ResumeModel> filterByIntendAndGender(@Param("intendId") Integer intendId, @Param("gender") String gender, @Param("pageNumber") int pageNumber, @Param("pageSize") int pageSize);
    long countFilterByIntendAndGender(@Param("intendId") Integer intendId, @Param("gender") String gender);

    List<ResumeModel> findByAuth(@Param("authList") List<String> authList, @Param("pageNumber") int pageNumber, @Param("pageSize") int pageSize);
    long countFindByAuth(@Param("authList") List<String> authList);

    List<ResumeModel> getInBatch(List<Integer> idList);

    List<ResumePostRecord> findPostRecordByMember(@Param("memberId") Integer memberId, @Param("pageNumber") int pageNumber, @Param("pageSize") int pageSize);
    long countFindPostRecordByMember(@Param("memberId") Integer memberId);

    void updateTime(Integer resumeId);

    void increasePageView(Integer resumeId);
}