package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.SHPostCategoryModel;
import org.apache.ibatis.annotations.Param;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.cache.annotation.Caching;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ShPostCategoryModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_post_category
     *
     * @mbggenerated
     */
    @Caching(
            evict = {
                    @CacheEvict(value = "shPostCategoryCache", key = "'ShPostCategory:id:'.concat(#p0)"),
                    @CacheEvict(value = "shPostCategoryListCache", allEntries = true)
            }
    )
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_post_category
     *
     * @mbggenerated
     */
    @CacheEvict(value = "shPostCategoryListCache", allEntries = true)
    int insert(SHPostCategoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_post_category
     *
     * @mbggenerated
     */
    @CacheEvict(value = "shPostCategoryListCache", allEntries = true)
    int insertSelective(SHPostCategoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_post_category
     *
     * @mbggenerated
     */
    @Cacheable(value = "shPostCategoryCache", key = "'ShPostCategory:id:'.concat(#p0)")
    SHPostCategoryModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_post_category
     *
     * @mbggenerated
     */
    @Caching(
            evict = {
                    @CacheEvict(value = "shPostCategoryCache", key = "'ShPostCategory:id:'.concat(#p0.id)"),
                    @CacheEvict(value = "shPostCategoryListCache", allEntries = true)
            }
    )
    int updateByPrimaryKeySelective(SHPostCategoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_hand_post_category
     *
     * @mbggenerated
     */
    @Caching(
            evict = {
                    @CacheEvict(value = "shPostCategoryCache", key = "'ShPostCategory:id:'.concat(#p0.id)"),
                    @CacheEvict(value = "shPostCategoryListCache", allEntries = true)
            }
    )
    int updateByPrimaryKey(SHPostCategoryModel record);

    @Cacheable(value = "shPostCategoryListCache", key = "'ShPostCategory:all:'.concat(#p0).concat(':').concat(#p1)")
    List<SHPostCategoryModel> getAll(@Param("pageNumber") int pageNumber, @Param("pageSize") int pageSize);
}