package com.fh.taolijie.dao.mapper;

import com.fh.taolijie.domain.StuCertiModel;
import com.fh.taolijie.domain.StuCertiModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface StuCertiModelMapper {

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_certi
     *
     * @mbggenerated
     */
    int insert(StuCertiModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_certi
     *
     * @mbggenerated
     */
    int insertSelective(StuCertiModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_certi
     *
     * @mbggenerated
     */
    StuCertiModel selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_certi
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StuCertiModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_certi
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StuCertiModel record);

    List<StuCertiModel> findBy(StuCertiModel example);
    long countFindBy(StuCertiModel example);
}