package com.fh.taolijie.domain.quest;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fh.taolijie.domain.Pageable;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class QuestCoModel extends Pageable {
    private Integer id;

    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createdTime;

    private Integer memberId;

    private Integer questId;

    private String questTitle;

    public QuestCoModel() {}

    public QuestCoModel(int pn, int ps) {
        super(pn, ps);
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_quest.id
     *
     * @param id the value for collection_quest.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_quest.created_time
     *
     * @return the value of collection_quest.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_quest.created_time
     *
     * @param createdTime the value for collection_quest.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_quest.member_id
     *
     * @return the value of collection_quest.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_quest.member_id
     *
     * @param memberId the value for collection_quest.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_quest.quest_id
     *
     * @return the value of collection_quest.quest_id
     *
     * @mbggenerated
     */
    public Integer getQuestId() {
        return questId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_quest.quest_id
     *
     * @param questId the value for collection_quest.quest_id
     *
     * @mbggenerated
     */
    public void setQuestId(Integer questId) {
        this.questId = questId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_quest.quest_title
     *
     * @return the value of collection_quest.quest_title
     *
     * @mbggenerated
     */
    public String getQuestTitle() {
        return questTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_quest.quest_title
     *
     * @param questTitle the value for collection_quest.quest_title
     *
     * @mbggenerated
     */
    public void setQuestTitle(String questTitle) {
        this.questTitle = questTitle == null ? null : questTitle.trim();
    }
}